### ISSUE TITLE
TypeError: diffInput.replace is not a function

### ISSUE THREAD

**Issue by arnaspet** [rtfpessoa/diff2html#101]
So im trying to use this library with no success, in backend i do diff with `php`, first i tried `sebiastian/diff` library, after problems with it and google help i found that some people have same problems with that library too. So after that i have changed library to `neos/diff` but still same problems left.

i tried debugging this problem, is it suppose to call this function twice ? Because firstly diffInput is string ( data-diff) and second time its called diffInput is array.

[data-diff]: 
@@ -1,3 +1,1 @@
-data
 data
-data

javascript:
```javascript
  $('.proxy-diff').each(function(){
        if ($(this).data('diff') !== '') {
            var diff2htmlUi = new Diff2HtmlUI({diff: $(this).data('diff')});
            diff2htmlUi.draw(this.id, {matching: 'lines'});
        }
  });
```

Stack trace:
```
diff2html.js:2555 Uncaught TypeError: diffInput.replace is not a function
DiffParser.generateDiffJson @ diff2html.js:2555
Diff2Html.getPrettyHtml @ diff2html.js:2827
Diff2HtmlUI.draw @ diff2html-ui.js:37
(anonymous function) @ proxy_list_show.js:11
each @ jquery.js:374
each @ jquery.js:139
initRevisionDiffs @ proxy_list_show.js:8
init @ proxy_list_show.js:4j @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417I @ jquery.js:3433
```

**Comment by rtfpessoa** [comment]
Hi @arnaspet, 

I found a possible bug in the diff2html-ui leading to a possible bad behaviour.

You can avoid it by explicitly passing the `inputFormat`, and you can also use `$(this)`.

```js
        var diff2htmlUi = new Diff2HtmlUI({diff: $(this).data('diff')});
        diff2htmlUi.draw($(this), {
            inputFormat: 'json',
            matching: 'lines'
        });
```

When I get some time I will review the API and see if there are any more problems. In the meanwhile  try that fix.

**Comment by arnaspet** [comment]
ok thanks,
also it creates only empty wrapper:
```html
<div class="d2h-wrapper">
    
</div>
```
when i added `"--- a/sample\n+++ b/sample\n"` to start of string only then it started working.

**Comment by rtfpessoa** [comment]
@arnaspet do not close this for me not to forget to fix this.

Regarding the diff. That is expected. I only support unified diffs or the extended git diff version.

So you need to at least have : 
```
--- oldfilename
+++ newfilename
@@ .... @@
body
```

Your diff is currently not a valid unified diff.

Read more about it here:
http://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html#Detailed-Unified

**Comment by arnaspet** [comment]
@rtfpessoa Thanks ! Sorry for closing, missclicked it.

**Comment by rtfpessoa** [comment]
@arnaspet no problem 😄

**Comment by rtfpessoa** [comment]
Fixed in https://github.com/rtfpessoa/diff2html/commit/d3b053cae0fd40a4e0950fa17375b1d00d5c2848

Will be released soon.
