### ISSUE TITLE
Working online version of diff2html

### ISSUE THREAD

**Issue by kevinsimper** [rtfpessoa/diff2html#102]
I made a online version which I will use to embed diff2html on my blog with iframes. Soo much better when you are explaining code!

Works but giving a github diff url you it fetches it and shows it online.

https://github.com/kevinsimper/diff2html-example

**Comment by rtfpessoa** [comment]
Cool! I might even use the idea and add this as a feature of https://diff2html.xyz

**Comment by kevinsimper** [comment]
Yeah, no problem, the code is pretty simple, wondered why nobody had done similar before! 😄

**Comment by rtfpessoa** [comment]
@kevinsimper just did #107 using your idea.

If you can, take a look and let me know if you have any suggestions.

**Comment by rtfpessoa** [comment]
This is already online in https://diff2html.xyz/url.html?diff=https://github.com/rtfpessoa/diff2html/pull/106
