### ISSUE TITLE
Binary files are not included in files changed or diffs

### ISSUE THREAD

**Issue by GeorgePhillips** [rtfpessoa/diff2html#104]
It would be nice to show all files that have been changed in the diff. Even if this just shows "Binary file updated..." for each file. This would give a complete list of all changes. Happy to add this.

**Comment by rtfpessoa** [comment]
@GeorgePhillips I have one commit in my pc with some changes related to this. But I cannot find a full spec for the git diff, that contains all the possible sentences.

The one I have is `Binary files {OLD} and {NEW} differ`

**Comment by GeorgePhillips** [comment]
@rtfpessoa I think thats it. I can't find anything about either. We could change it to understand the new file mode code and fallback to say the rest of that files diff is unreadable.

https://github.com/jekyll/brand/commit/1401b66b3a6a938fb141e405323cbbd96d1f7c2a.diff

**Comment by rtfpessoa** [comment]
Fixed by #105 

Will release soon. Sorry for the delay, been busy lately.

**Comment by rtfpessoa** [comment]
Released as version `diff2html@2.0.7`
