### ISSUE TITLE
Compare two strings of html

### ISSUE THREAD

**Issue by webchaz** [rtfpessoa/diff2html#108]
Looking at the API it seems there's only one input option, what format should this input be to compare two strings?

**Comment by rtfpessoa** [comment]
Hi @webchaz, this library's purpose is only to parse git or unified diff output and generate pretty HTML.

The diff part must be generated by any outside tool such as git or diff or any other compatible tool.

Even though, you can use [diff2html-cli](https://github.com/rtfpessoa/diff2html-cli) to do it.

Ex:

```
npm install -g diff2html-cli
diff2html -- --no-index file1.html file2.html
```

Note: Run exactly as described the `--` are meant to separate the attributes of diff2htm-cli from the underlying git command to invoke.

Closing, let me know if you have any other questions.
