### ISSUE TITLE
binary file diff

### ISSUE THREAD

**Issue by frostbane** [rtfpessoa/diff2html#115]
Browser crashes when trying to parse a large diff of a binary file.

If the file is small, it shows nothing.

![0](https://cloud.githubusercontent.com/assets/12523422/20204746/b83da8de-a815-11e6-9870-65781ed8bd73.png)

I suggest that instead of parsing it, return the SHA-256 (or what not) or return "binary file", or anything that can be displayed to the user.

![1](https://cloud.githubusercontent.com/assets/12523422/20204750/c24f412a-a815-11e6-852d-4a2e32688f39.png)

**Comment by rtfpessoa** [comment]
Did a possible fix in #116. Do you have any open source project that I can test on?

**Comment by rtfpessoa** [comment]
I am considering this fixed. If you have any more questions let me know.

**Comment by frostbane** [comment]
I'm terribly sorry I have been very busy with the end of the year stuff.

I actually made a test project but never got the chance to test
[https://bitbucket.org/isochrone/binary](https://bitbucket.org/isochrone/binary)
