### ISSUE TITLE
diff2 v 2.0.3, not working for large files (size 12MB)

### ISSUE THREAD

**Issue by soumali** [rtfpessoa/diff2html#117]
Hi,

I am working on Oracle Linux 6.7. 
diff2html v 2.0.3 fails to run for a large diff file of size 12MB, with below exception:

<--- Last few GCs --->

    5922 ms: Mark-sweep 824.6 (1456.2) -> 824.3 (1456.2) MB, 177.3 / 0 ms [allocation failure] [scavenge might not succeed].
    6114 ms: Mark-sweep 824.3 (1456.2) -> 824.3 (1456.2) MB, 192.1 / 0 ms [allocation failure] [scavenge might not succeed].
    6327 ms: Mark-sweep 824.3 (1456.2) -> 824.3 (1456.2) MB, 213.2 / 0 ms [last resort gc].
    6534 ms: Mark-sweep 824.3 (1456.2) -> 824.3 (1456.2) MB, 206.3 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1a2035d37399 <JS Object>
    2: levenshtein [/usr/local/node-v4.2.1-linux-x64/lib/node_modules/diff2html-cli/node_modules/diff2html/src/rematch.js:~24] [pc=0x1359b297717d] (this=0x1a2035db7909 <JS Global Object>,a=0x98048a53f81 <Very long string[56665]>,b=0x98048a53fa9 <Very long string[56664]>)
    3: /* anonymous */(aka /* anonymous */) [/usr/local/node-v4.2.1-linux-x64/lib/node_modules/diff2html-cli/node_modules/dif...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
^CAborted (core dumped)

Requesting your help

**Comment by rtfpessoa** [comment]
That seems to be a problems with the matching algorithm.

Try disabling it with large files. https://github.com/rtfpessoa/diff2html#configuration

Use option matching = none

**Comment by soumali** [comment]
@rtfpessoa Thanks a lot! It seems to be working. I am using the command line version. Adding option 
"--matching "none" ", made it run successfully:

diff2html  -F  <output_html> --matching "none" -i file -- <input_diff>

**Comment by soumali** [comment]
Not able to view complete file name in generated html from diff. Filename gets truncated in generated html
Eg. <DirectoryName>/FileName<truncated>.... 
Is there any way to display entire filename in the generated html?
