### ISSUE TITLE
File Name inside generated html gets truncated

### ISSUE THREAD

**Issue by soumali** [rtfpessoa/diff2html#118]
Not able to view complete file name in generated html from diff. Filename gets truncated in generated html
Eg. <DirectoryName>/FileName<truncated>.... 
Is there any way to display entire filename in the generated html?

**Comment by rtfpessoa** [comment]
What version are you using? Can you provide an example?

**Comment by soumali** [comment]
\<DirectoryName\>/FileName\<truncated\>....

**Comment by rtfpessoa** [comment]
Do you have any suggestions about how to fix this?

#84 Was kind of a fix but the contributor dropped it. Since it still had some corner cases.

I am open to any prs.

**Comment by soumali** [comment]
Thanks for your comment @rtfpessoa. I will revert back with the solution if any.
