### ISSUE TITLE
Output HTML displays binary file name header as in input diff, but shows diff of previous source file present in same input diff

### ISSUE THREAD

**Issue by soumali** [rtfpessoa/diff2html#119]
In diff2html v2.0.3, If diff contains Binary Files, post diff2html exec, output html displays name of binary file in header as present in input diff, but difference of previous source file that is present in the same diff:

Eg.
Input diff:
![image](https://cloud.githubusercontent.com/assets/3131481/20875497/3f2f391a-bae1-11e6-8db1-f6ed69eef55f.png)

Output HTML:
![image](https://cloud.githubusercontent.com/assets/3131481/20875427/c5284e54-bae0-11e6-8ca6-3842c5a62b58.png)

**Comment by rtfpessoa** [comment]
@soumali can you try 2.0.11 version?

**Comment by rtfpessoa** [comment]
I am considering this fixed. If you are still experiencing problems let me know.
