### ISSUE TITLE
Right side of diff being highlighted as comments

### ISSUE THREAD

**Issue by emarcotte** [rtfpessoa/diff2html#120]
Hello,

I'm using 2.0.10 and have noticed that some files seem to cause an issue where the right hand side of a side-by-side diff is considered to all be a comment:

![image](https://cloud.githubusercontent.com/assets/249390/20930019/0660817a-bb9a-11e6-9a96-ec324ab52612.png)

I have not figured out what actually triggers the issue, I spent some time trying to step through the line-by-line highlighting but nothing seemed out of the ordinary. As you can see in the screenshot, on the left it used the language properly, but for some reason it doesn't on the right. Hopefully I can find some common thread between the files that are affected (seems to be very small number of them for me). If it's helpful I can try to attach a reproducing diff file as well.

This is the code I'm using to generate the diff:

```
                        var diff2htmlUI = new Diff2HtmlUI({ diff: "big ol diff string here" });
			diff2htmlUI.draw('#diff-div', {
				inputFormat: 'json',
				showFiles: true,
				matching: 'lines',
				outputFormat: 'side-by-side',
				synchronisedScroll: true
			});
			diff2htmlUI.highlightCode('#diff-div');
			diff2htmlUI.fileListCloseable('#diff-div', true);
```

I am using highlightjs 9.7.0, but it also failed with 9.8.0.

Let me know if there's any more info I can provide

**Comment by rtfpessoa** [comment]
@emarcotte can you provide one diff example for me to test?

**Comment by emarcotte** [comment]
Try this one: [diff2.zip](https://github.com/rtfpessoa/diff2html/files/649679/diff2.zip)

It's got the whole page (including json diff). I'm wondering if my diff generation tool is not generating the right out put, actually. I have hackedly tried to get perforce to spit out git-like diffs (I don't have access to p4-git or whatever it is called).

**Comment by rtfpessoa** [comment]
@emarcotte, I cannot find out what can be the problem. But you can try to add more context lines when you get the diff command using something like `-U20`.

This is a problems of using highlight in partial code.

For now there is not option for me to get around this.
