### ISSUE TITLE
Not parse `svn diff --git` output right

### ISSUE THREAD

**Issue by zjh1943** [rtfpessoa/diff2html#126]
When parse `svn diff --git` output, we will get errors below:

### parse the wrong file name

svn diff --git will output header like this:

diff --git a/color_doc.docx b/color_doc.docx
--- a/color_doc.docx	(nonexistent)
+++ b/color_doc.docx	(revision 10)

We got b/color_doc.docx (revision 10) as file name.

### Not support 5 characters file mode

`svn diff --git` will output file mode like that:
```
new file mode 10644
```
The mode number has only 5 characters, not 6. So `diff-parser` do not recognized it.

**Comment by rtfpessoa** [comment]
Fixed with #125 right?

**Comment by zjh1943** [comment]
Yes.
