### ISSUE TITLE
How can I import 'Diff2HtmlUI' in Node.js?

### ISSUE THREAD

**Issue by nonelove** [rtfpessoa/diff2html#134]
Hi,

In 'package.json', only the 'Diff2Html' module is exported. Could you export 'Diff2HtmlUI', too?

Thanks.

**Comment by rtfpessoa** [comment]
Hi @nonelove,

If you are referring to the field "main", as it says in the npm website we should only export one JS file there.

**Comment by masad-frost** [comment]
You can import both and re-export them in a common module/file?
