### ISSUE TITLE
synchronisedScroll doesn't work with Diff2Html.getPrettyHtml

### ISSUE THREAD

**Issue by Dropth** [rtfpessoa/diff2html#135]
Hi there !

### Environement

  * OS: Windows 10
  * diff2html version: 2.3.0
  * Using diff2html directly or using diff2html-ui helper: diff2html directly

### Problem

When using `Diff2Html.getPrettyHtml`, if we set true to the synchronisedScroll, it dosn't work. 

### CodePen Example

[Diff2Html.getPrettyHtml Example](https://codepen.io/anon/pen/RZbWYG?editors=0010#0)

In any case, thanks for your work !

**Comment by rtfpessoa** [comment]
To have synchronized scroll you need JS and for that reason it only works with the diff2html UI helper. Also you need to have JQuery for it to work. Check the examples in the Readme on how to use it.

I updated the README for it to be more explicit.
