### ISSUE TITLE
Can't generate HTML for minified Javascript diff

### ISSUE THREAD

**Issue by isaac** [rtfpessoa/diff2html#142]
### Step 0: Describe your environment

  * OS: macOS Sierra (10.12.6)
  * diff2html version: 2.3.1
  * Using diff2html directly or using diff2html-ui helper: directly
  * Extra flags: --matching "none"

#### Steps to reproduce:

```bash
git clone git@github.com:isaac/jquery-min-diff.git
cd jquery-min-diff
git diff master..origin/v3.2.1 > jquery-min.diff
diff2html -F jquery-min.html --matching "none" -i file -- jquery-min.diff
```

OR try and load the same diff using the demo website here: https://diff2html.xyz/demo?diff=https://github.com/isaac/jquery-min-diff/pull/1

#### diff example:

https://github.com/isaac/jquery-min-diff/pull/1

#### Observed Results:

CPU use spikes to 100% and stays there - command just hangs and never completes. Same thing happens when I load the above pull request using the demo website like this: https://diff2html.xyz/demo?diff=https://github.com/isaac/jquery-min-diff/pull/1 - in this case the CPU spikes but the browser eventually kills the tab.

#### Expected Results:

I expected diff2html to generate an HTML version of the diff above

#### Relevant Code:

See Steps to reproduce above

**Comment by isaac** [comment]
@rtfpessoa just wondering - were you able to reproduce this bug yourself?

Is this something you have seen before?

I'm happy to help fix this, but I don't much experience debugging these kind of issues with Javascript libraries. If you could point me in the right direction that would be much appreciated :)

**Comment by rtfpessoa** [comment]
Since this happens online it can be a problem.

Still not sure yet where exactly it happens I would also have to check.

You can for example try to use the chrome debugger to see where it breaks. If I get some time I will also take a look.

**Comment by isaac** [comment]
@rtfpessoa I did some profiling of the CLI process - here is the gist: https://gist.github.com/isaac/87a46b2cd4ecc0aa90cc2d97e12f1398

I generated this by running this command: `NODE_ENV=production node --prof /usr/local/bin/diff2html -F jquery-min.html --matching none -i file -- jquery-min.diff` in the same directory where I generated the diff above. This then creates a log file which I processed with this command:`node --prof-process isolate-0x104001600-v8.log > processed.txt`

More information here: https://nodejs.org/en/docs/guides/simple-profiling/

I also inspected the CLI process using Chrome by running this command: `NODE_ENV=production node --inspect /usr/local/bin/diff2html -F jquery-min.html --matching none -i file -- jquery-min.diff`

Then I opened this URL in Chrome: chrome://inspect

I could then record an allocation profile for the Javascript functions - see this screenshot:

<img width="1440" alt="profile" src="https://user-images.githubusercontent.com/2070/31416552-562d214c-ae86-11e7-80c5-8d8f0c313373.png">

I don't really know how to interpret these results but maybe it means something to you.

Please let me know if the above is helpful and if there is anything else I can do to help fix this issue :)
