### ISSUE TITLE
Incorrect code highlight when a previous chunk end with a block comment 

### ISSUE THREAD

**Issue by tdurieux** [rtfpessoa/diff2html#148]
### Step 0: Describe your environment

  * OS: Ubuntu
  * diff2html version: 2.3.1
  * Using diff2html directly or using diff2html-ui helper: diff2html-ui
  * Extra flags: 
```js
var diff2htmlUi = new Diff2HtmlUI({ diff: diff });
diff2htmlUi.draw($(elem), {inputFormat: 'java', showFiles: false, matching: 'lines'});
diff2htmlUi.highlightCode($(elem));
```

### Step 1: Describe the problem:

The code of the second chunk is highlighted as a comment because the first chunk ends with a block comment.

![image](https://user-images.githubusercontent.com/5577568/31931366-4cd02262-b8a3-11e7-937f-121d798018e1.png)

#### diff example:

  ```diff
diff --git a/src/com/google/javascript/jscomp/TypedScopeCreator.java b/src/com/google/javascript/jscomp/TypedScopeCreator.java
index 92d8715..f9943a1 100644
--- a/src/com/google/javascript/jscomp/TypedScopeCreator.java
+++ b/src/com/google/javascript/jscomp/TypedScopeCreator.java
@@ -417,6 +417,7 @@ final class TypedScopeCreator implements ScopeCreator {
      * For more information, see
      * http://code.google.com/p/closure-compiler/issues/detail?id=314
      */
+    private List<Node> lentObjectLiterals = null;
 
     /**
      * Type-less stubs.
@@ -544,6 +545,13 @@ final class TypedScopeCreator implements ScopeCreator {
       }
 
       // Analyze any @lends object literals in this statement.
+      if (n.getParent() != null && NodeUtil.isStatement(n) &&
+          lentObjectLiterals != null) {
+        for (Node objLit : lentObjectLiterals) {
+          defineObjectLiteral(objLit);
+        }
+        lentObjectLiterals.clear();
+      }
     }
  ```

#### Relevant Code:

  ```js
var diff2htmlUi = new Diff2HtmlUI({ diff: diff });
diff2htmlUi.draw($(elem), {inputFormat: 'java', showFiles: false, matching: 'lines'});
diff2htmlUi.highlightCode($(elem));
  ```

**Comment by rtfpessoa** [comment]
@tdurieux this is a know issue, but is also the best I could do with the partial information available in the diff. If you want to take a look at the code in https://github.com/rtfpessoa/diff2html/blob/master/src/ui/js/diff2html-ui.js#L82 and make any suggestions, fell free to open a PR.

NOTE: If you retrieve a diff with more context can also help but you will have bigger diffs.
