### ISSUE TITLE
Is it possible to use diff2html for showing differences of two local files

### ISSUE THREAD

**Issue by astridx** [rtfpessoa/diff2html#163]
Thank you very much for providing diff2html. I like the views (output Formats).

I would like to show differences of two local files. Can you suggest a way to create the format of the input data: 'diff' or 'json'?

**Comment by rtfpessoa** [comment]
Hi @astridx,

From what I understood what you want is something like this:

`git diff --no-index file1 file2 | diff2html -i stdin`

Let me know if it worked.

**Comment by scottix** [comment]
Aww I see how this work now. This is not very clear.

My thought was you could diff any files but turns out it uses git diff on the backend. I understand you can do this sort of hack to do local files but having a native way to do this would be very beneficial and I think it could expand use cases outside of git.

**Comment by astridx** [comment]
@rtfpessoa Thank you for your answer. Yes, this works. But like @scottix I had the hope, that there is a way without the need that git is installed on a machine.

**Comment by scottix** [comment]
@astridx Hey so we have been working with it more there is another way to diff local files

`diff -u file1 file2 | diff2html -i stdin`

**Comment by astridx** [comment]
@scottix Yes, you are right.
I close this issue, as the question is answered.

**Comment by rtfpessoa** [comment]
@astridx the idea here is mostly to do a parser and html generator for unified diffs. After this we also have git diff as an extra.
The other project `diff2html-cli` is a wrapper for this project with a helper to get diffs from git.

In this case like you checked you can also get the diffs from diff unix tool or from any other `Unified Diff` compatible generator.

**Comment by rahul-ecsion** [comment]
Is is possible to see all content in file from diff files by scrolling it?

**Comment by rahul-ecsion** [comment]
@rtfpessoa  Is is possible to see all content in file from diff files by scrolling it?

**Comment by rtfpessoa** [comment]
@rahul-ecsion not sure what you mean.

You mean to show more lines that did not change (context lines)?
If that is the case, you can use options line `-U1000` for git diff. diff2html only renders what it gets form the input.
If you want more you need to get it into the original diff.
