### ISSUE TITLE
Is it possible to beautify just the patch of a single file

### ISSUE THREAD

**Issue by ahtahkr** [rtfpessoa/diff2html#164]
<h2>This is just a question.</h2> Is it possible to beautify just the patch of a single file. The patch is a string: <br><br><b><i>"@@ -0,0 +1,26 @@ +## Contributing + +[fork]: https://github.com/github/fetch/fork +[pr]: https://github.com/github/fetch/compare + +Hi there! We're thrilled that you'd liske to contribute to this project. Your help is essential for keeping it great. + +Contributions to this project are [released](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) to the public under the [project's open source license](LICENSE). + +## Submitting a pull request + +0. [Fork][fork] and clone the repository +0. Create a new branch: `git checkout -b my-branch-name` +0. Make your change, push to your fork and [submit a pull request][pr] +0. Pat your self on the back and wait for your pull request to be reviewed and merged. + +Here are a few things you can do that will increase the likelihood of your pull request being accepted: + +- Keep your change as focused as possible. If there are multiple changes you would like to make that are not dependent upon each other, consider submitting them as separate pull requests. +- Write a [good commit message](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). + +## Resources + +- [How to Contribute to Open Source](https://opensource.guide/how-to-contribute/) +- [Using Pull Requests](https://help.github.com/articles/about-pull-requests/) +- [GitHub Help](https://help.github.com)"</i></b><br><br>
![capture](https://user-images.githubusercontent.com/29711462/36509985-20dbf414-1727-11e8-9137-7c5f676fd534.PNG)

**Comment by amaralDaniel** [comment]
Hey! Were you able to do it?

**Comment by ahtahkr** [comment]
No, I decided to go with the patch for the entire commit
