### ISSUE TITLE
diffJson not overwritten if a new Diff2HtmlUI is instantiated and cfg.diff = ""

### ISSUE THREAD

**Issue by AGiesey** [rtfpessoa/diff2html#165]
### Step -1: Before filling an issue check out troubleshooting section

  * Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

  * OS: doesn't matter
  * diff2html version: 2.3.3
  * Using diff2html directly or using diff2html-ui helper: diff2html directly
  * Extra flags: _____

#### Steps to reproduce:

  1. Implement diff2Html within an AngularJs component
  2. instantiate a new Diff2HtmlUI({ diff: [some content] })
  3. Load a diff that has no content, such as a file that's been renamed Diff2HtmlUI({ diff: ""}) 
  4. The value in diffJson is not overwritten because the empty string is falsy. 

#### Observed Results:

  * The file rename has a diff of the last file a user looked at

#### Expected Results:

  * the diff to be blank and just the header, file name and renamed tag displayed

#### Relevant Code:

  ```
  (function() {
      var highlightJS = require('./highlight.js-internals.js').HighlightJS;

      var diffJson = null;
      var defaultTarget = 'body';
      var currentSelectionColumnId = -1;

     function Diff2HtmlUI(config) {
         var cfg = config || {};

        if (cfg.diff) {
            diffJson = Diff2Html.getJsonFromDiff(cfg.diff);
        } else if (cfg.json) {
            diffJson = cfg.json;
    }
  ```

**Comment by rtfpessoa** [comment]
@AGiesey I am not completly sure what you mean.

But if you invoke diff2html with `{ diff: ""}` it will not show anything since that is empty.
diff2html is just a unified diff parser and generator of html from the parser output.

Does this make sense? If not can you extend a bit on the issue?

**Comment by AGiesey** [comment]
If you invoke it with an empty string after it has already been invoked
with a value that works, then that value will be displayed because it still
exists until the browser is reloaded. There is nothing that overwrites the
value of  diffJson if you pass Diff2Html an empty string. So if diffJson is
set that is what will be displayed, does that make sense?

**Comment by rtfpessoa** [comment]
Can you provide a code example that replicates the issue?

**Comment by AGiesey** [comment]
Ya, it might be a couple of days tho. Thanks

**Comment by rtfpessoa** [comment]
If you get something to test I will re-open.
