### ISSUE TITLE
Use random output file names instead of fixed diff.html

### ISSUE THREAD

**Issue by myelsukov** [rtfpessoa/diff2html#166]
Fixed (default) output file name (e.g. file:///private/var/folders/xz/jt5vrgxj3nb7vnb6hhp8lrvsqy78qg/T/diff.html) makes impossible looking into diffs from different projects at the same time because they override each other.

Please use either random default output file names or make output file name a function of the git repository name.

**Comment by rtfpessoa** [comment]
@myelsukov that refers to https://github.com/rtfpessoa/diff2html-cli and not this repo. Still it could be a nice addition. Feel free to send a PR there.

**Comment by myelsukov** [comment]
Done: https://github.com/rtfpessoa/diff2html-cli/issues/37
