### ISSUE TITLE
The json format is not explained in the README

### ISSUE THREAD

**Issue by AndersBillLinden** [rtfpessoa/diff2html#168]
diff2html supports two input formats: diff and json, but the README at
https://github.com/rtfpessoa/diff2html
does not explain or examplify those formats.

**Comment by rtfpessoa** [comment]
@AndersBillLinden the diff format is a unified diff and the json is the one generated by the method `getJsonFromDiff`.

I will try to make it more explicit.

**Comment by AndersBillLinden** [comment]
Wow, fast answer. Is there some way of just passing two strings?

**Comment by rtfpessoa** [comment]
diff2html only aims to parse and generate pretty html from a unified diff.
But there are plenty of tools doing the diff part.

For example you can just use diff2html-cli published in npmjs.org and do:
`git diff --no-index file1 file2 | diff2html -i stdin`

**Comment by AndersBillLinden** [comment]
What I need is a javascript library that I can use from a webpage that will give me the diff view. I am getting the impression that this will rather create a webpage.

**Comment by AndersBillLinden** [comment]
Maybe I should use https://github.com/google/diff-match-patch instead

**Comment by rtfpessoa** [comment]
I guess it depends on what are you needs.
