### ISSUE TITLE
existHunkHeader

### ISSUE THREAD

**Issue by oldrich-s** [rtfpessoa/diff2html#172]
The `existHunkHeader` in

https://github.com/rtfpessoa/diff2html/blob/master/src/diff-parser.js#L171

has probably a bug as it fails on e.g.:

```
diff --git a/organization/c051/lab-oversigt/data/beton - robot.json b/organization/c051/lab-oversigt/data/beton - varemodtagelse.json
similarity index 100%
rename from organization/c051/lab-oversigt/data/beton - robot.json
rename to organization/c051/lab-oversigt/data/beton - varemodtagelse.json
diff --git a/organization/c051/lab-oversigt/data/beton - varmudvikling.json b/organization/c051/lab-oversigt/data/beton - varmudvikling.json
index 875930f..8b537c7 100644
--- a/organization/c051/lab-oversigt/data/beton - varmudvikling.json\t
```

When the line is set to `rename to...`, it overflows into the next `diff` and `---`, so `existHunkHeader` responds `true` which it should not.

The second thing is that `possibleNewName` and `possibleOldName` are wrong as they do not take into account the spaces in the paths - but that would probably be fixed if the `existHunkHeader` worked.

PS: Is the `existHunkHeader` necessary at all?

EDIT:

I guess that `utils.startsWith(line, 'diff')` should be `utils.startsWith(diffLines[idx], 'diff')`

**Comment by rtfpessoa** [comment]
Seems like the spaces might be the issue.
Regarding `possibleNewName` it is used to have the best of Git and Unified.

I am not sure I understand your last EDIT.

Any PRs with a fix are welcome.

**Comment by rtfpessoa** [comment]
Could not replicate, if you get a full example that I can use I will try to fix it.
