### ISSUE TITLE
Add file info to list of file. (Modified date, ...)

### ISSUE THREAD

**Issue by Vintic** [rtfpessoa/diff2html#176]
Hi,
Is there a way to add file info (like modified date) in a file list section

I use Jenkins for deployment. And would like to check (highlight) files that was modified on production from last deployment.

Usage:
I want to highlight files that has modified date greater than specific date (date of last deploy to production). And check them first.

**Comment by rtfpessoa** [comment]
I would not mind adding a flag/option allowing to sort the files by some rule, date could be one of them.
PRs are welcome.

**Comment by rtfpessoa** [comment]
Closing this to keep the discussion in #152.
