### ISSUE TITLE
Use diff2html library

### ISSUE THREAD

**Issue by sidagarwal** [rtfpessoa/diff2html#184]
Hi Rodrigo.

This is Sid from Seattle, WA. I am looking to use your diff2html library in one of my project I am building for Salesforce app exchange marketplace. 

Use case - Allow users to compare 2 piece of codes side-by-side. Your application seems to be perfect fit for this.

Let me know, if its fine to for me to use diff2html library code for free.

P.S. Apologies for contacting you here. I didn't see any other option to contact you directly.

Thanks
Sid

**Comment by rtfpessoa** [comment]
Sure, feel free to use. If it is something public you can even add it to this list: https://diff2html.xyz/#users

**Comment by sidagarwal** [comment]
Thank you so much.

**Comment by rtfpessoa** [comment]
Maybe this: https://www.npmjs.com/package/unidiff

**Comment by sidagarwal** [comment]
Thanks. I will take a look.
