### ISSUE TITLE
trim lodash dependence

### ISSUE THREAD

**Issue by starpit** [rtfpessoa/diff2html#186]
### Step 0: Describe your environment

  * OS: any
  * diff2html version: 2.5.0
  * Using diff2html directly or using diff2html-ui helper: directly
  * Extra flags: _____

### Step 1: Describe the problem:

lodash is pulled in, in its entirety, via the package.json depenendence. #160 covered the dynamic part, but did not address the unused weight of the full lodash npm.

the fix is fairly straightforward, as the lodash team provides a separate lodash.merge npm, and this appears to be the only use of lodash by diff2html.

```bash
diff2html❯ du -sh node_modules/lodash.merge
 64K	node_modules/lodash.merge

diff2html❯ du -sh node_modules/lodash
4.8M	node_modules/lodash
```

PR #187

**Comment by rtfpessoa** [comment]
Released as version 2.7.0
