### ISSUE TITLE
could diff2html-ui provide a jump link like the origin svn diff shows

### ISSUE THREAD

**Issue by PhoebeWho** [rtfpessoa/diff2html#189]
* OS: linux
  * diff2html version: lastest
  * Using diff2html directly or using diff2html-ui helper: diff2html-ui helper
  * Extra flags: _____

Hi, I met a problem when using diff2html-ui (side-by-side). Diffs of data.py which contains a dict format data with long values. I want to know the key of the changed values, so I set svn diff -U500 to guarantee the key is shown. But then the content is too long to search every diff.

My problem is could diff2html-ui provide a jump link like the origin svn diff shows? Given a list of jump links on the left side or something like that...

Thank you very much!

**Comment by rtfpessoa** [comment]
@PhoebeWho I am not sure I understand your question. Can you provide an example?

**Comment by PhoebeWho** [comment]
Thank you very much for your reply.

In short, I mean tags or buttons function like the "Next difference" in origin svn diff show in TortoiseSVN.
![image](https://user-images.githubusercontent.com/7943460/52997886-b92ed300-345c-11e9-9c72-799042d03ec3.png)

Is it possible that diff2html provide a similar function?

**Comment by rtfpessoa** [comment]
@PhoebeWho that should not be hard to do.

If you take a look at https://github.com/rtfpessoa/diff2html/blob/master/src/ui/js/diff2html-ui.js#L43, maybe something similar could be done for navigating between files. If JS added a btn discovering the next and previous would be easy.

Feel free to send a PR.

**Comment by PAX523** [comment]
We need this feature in our environment, too. Alternatively, a minimap would also help.

**Comment by rtfpessoa** [comment]
Hmm, do you have any idea on how we could approach that?

**Comment by PAX523** [comment]
Unfortunately, I have no much JavaScript experience. Otherwise, I would conern myself with that feature.

**Comment by rtfpessoa** [comment]
@PAX523 ok let's see if I get some time to pick this and maybe some idea appears.
