### ISSUE TITLE
Is there anyway to style the @@-2, +4@@ ?

### ISSUE THREAD

**Issue by vanessadnguyen** [rtfpessoa/diff2html#194]
Because of the accessibility requirement, I have a need to make the @@-2, +4@@ to be darker. Is there anyway to style the @@-2, +4@@ ?

Thanks,
Vanessa

**Comment by vanessadnguyen** [comment]
Never mind. I figured out I can just change the following css class:
.d2h-info

**Comment by rtfpessoa** [comment]
@vanessadnguyen that should be the easiest way. Nice you got it.
