### ISSUE TITLE
Possible render bug when rendering $

### ISSUE THREAD

**Issue by whyboris** [rtfpessoa/diff2html#195]
diff2html-cli `2.7.0`
using `diff2html -s side` command with the _cli_
Mac OS _High Sierra_ `10.13.6`
Angular project, working in an _html_ file

Actual code change:
```
[listSubject]="magazineDate$"
```

Diff output in HTML:
```
[listSubject]="magazineDatequot;
```

Note that `$"` has become `quot;`

When doing `git diff` the diff renders correctly: `[listSubject]="magazineDate$"`

**Comment by rtfpessoa** [comment]
Weird. There must be a bug somewhere.
Need to find some time to do a test and debug it.
-- 
Best Regards,
Rodrigo Fernandes

**Comment by rtfpessoa** [comment]
Will be available in the next release
