### ISSUE TITLE
Diff Ignoring Whitespaces

### ISSUE THREAD

**Issue by piacenti** [rtfpessoa/diff2html#197]
I'm using a unified diff generator that apparently keeps whitespace differences. Does diff2Html have any way to ignore whitespaces or that has to be done at the diff generation step? Also any libraries out there that generate unified diff ignoring whitespaces? I couldn't find one.

**Comment by rtfpessoa** [comment]
Not sure if this is what you need but you can choose `matching` with value `word` as described in the README to have bigger matches when rendering. Nothing tther than that.

**Comment by piacenti** [comment]
I tried that but saw no differences for tree specific text I was dealing with. It was some xml that had app the same data with only difference in formatting (tabs vs spaces)

**Comment by rtfpessoa** [comment]
Then I think there is nothing easy we can do. If you feel like this could be a post processing feature I think that would be ok and PRs are welcome.
