### ISSUE TITLE
Question: access to old and new file names in templates?

### ISSUE THREAD

**Issue by emarcotte** [rtfpessoa/diff2html#199]
### Step 1: Describe the problem:

Background: I'm trying to make a template for the file list to list files to show a hierarchy of directories to the left of the diff(s). The goal is to mimic what bitbucket does for its diff viewer.  So far I've gotten this working for simple cases by post processing the DOM.

Question: I'm stumbling a bit on what to do with file names that get transformed via  PrinterUtils.prototype.getDiffName. As far as I can tell I can only get access to the transformed name in a template. Is there any appetite for adding a way to exposes the A and B names and/or secret mechanism I can use in the templates to get them already? Worst case scenario I can try to un-transform the filename, but wanted to make sure I wasn't missing something.

Thanks, 
Eugene

**Comment by rtfpessoa** [comment]
I think it could be nice to delay the `PrinterUtils.prototype.getDiffName` to as late as the template drawing and allow for better templates. Feel free to send a PR.

**Comment by emarcotte** [comment]
Cool. I'll see if I can find some time in the next few weeks to try that out.
