### ISSUE TITLE
Vue.js with diff2html-ui

### ISSUE THREAD

**Issue by ChihYuLin** [rtfpessoa/diff2html#205]
* OS:  Win 10
  * diff2html version: 2.7.0
  * Using diff2html directly or using diff2html-ui helper: diff2html-ui helper
  * Extra flags: help wanted

Hi, I tried diff2html-ui in vue.js but it didn't work.
I've successfully used diff2html at first and can use prettyHtml correctly.
But when I use diff2html-ui like:
```
<template>
  <div id="htmlUI">
  </div>
</tmplate>

<script>
import { Diff2HtmlUI } from 'diff2html/dist/diff2html-ui'
......
mounted () {
  const diff = {diff: 'diff xxxxxxx'} // Too long so I omit it here, I've test it worked for diff2html
  var diff2htmlUi = new Diff2HtmlUI(diff)
  diff2htmlUi.draw('#htmlUI', {inputFormat: 'json', showFiles: true, matching: 'lines'})
  diff2htmlUi.highlightCode('#htmlUI')
}
......
</script>
```

It never worked as the error message went like:
__WEBPACK_IMPORTED_MODULE_0_diff2html_dist_diff2html_ui__.Diff2HtmlUI is not a constructor

I also tried to use:
1. Diff2HtmlUI.Diff2HtmlUI(diff)
2. Diff2HtmlUI(diff)
None of them worked, 
I got error messages that indicated Diff2HtmlUI is neither a constructor
nor a function.

I thought that in diff2html-ui.js, Diff2HtmlUI is exposed:
```
  module.exports.Diff2HtmlUI = Diff2HtmlUI;
  // Expose diff2html in the browser
  global.Diff2HtmlUI = Diff2HtmlUI;
```

So where did I misunderstand this?
Could anyone give an example that how I could run diff2html-ui within vue.js?

Thanks!

**Comment by rtfpessoa** [comment]
@ChihYuLin, diff2html-ui is a set of helpers to manipulate the DOM with jQuery. For this reason it will not work with Vue.
To get it working you would have to adapt the functions but even that would probably lead to a completely different approach.

If you are interested maybe creating diff2html-vue could be the way. The code is not complicate there, let me know if you need help understanding.

Fell free to send a PR.
