### ISSUE TITLE
Output is not printing-friendly

### ISSUE THREAD

**Issue by sabi0** [rtfpessoa/diff2html#206]
### Step 0: Describe your environment

  * OS: Win 7 + Firefox 66
  * diff2html version: whatever is used by the online demo at diff2html.xyz

### Step 1: Describe the problem:

Printing diff2html output does not preserve color highlighting and clips long lines.

I wanted to print some diff's to review them "pen and paper" style while being offline. But this turned out to be infeasible with diff2html output.

#### Steps to reproduce:

  1. Open a demo page https://diff2html.xyz/demo.html?diff=https://github.com/rtfpessoa/diff2html/pull/106
  2. Print it (or open a Print preview)

#### Observed Results:

  * Background coloring is lost (even though it is enabled for printing in Page setup in the browser). The only parts left of it are tiny stripes on the left.
  * Long lines are clipped on the right side of the rendered output
  * Two columns with line numbers are merged into one

![image](https://user-images.githubusercontent.com/11509875/56037165-f746c580-5d2e-11e9-8a28-684aa7b664c0.png)

#### Expected Results:

  * Printed version should have the same coloring and layout as the "live" one
  * Long lines should be wrapped to avoid clipping
  * Printing style could use the whole page width to waste less paper

![image](https://user-images.githubusercontent.com/11509875/56037028-a8009500-5d2e-11e9-8b1b-73c9d44e3efb.png)

**Comment by rtfpessoa** [comment]
Hi @sabi0,
I actually never thought of that use case.

1. Since highlight is only done in the browser using DOM manipulation by highlight.js is normal that it does not get printed.
2. Wrapping is mostly a CSS problem, due to the way the HTML and CSS are done it is hard to achieve it with the current setup.

If you feel like working on improving any of these things I would gladly accept the PR.

**Comment by rtfpessoa** [comment]
Since `2.` is related to https://github.com/rtfpessoa/diff2html/issues/99 and `1.` is kind of an out of scope case closing it for now.
If someone feels like thinking about this let me know.
