### ISSUE TITLE
Rust Port

### ISSUE THREAD

**Issue by enzious** [rtfpessoa/diff2html#208]
@rtfpessoa I'm porting this library to rust and I was wondering if it would be alright to use the same name, diff2html.

Thanks.

**Comment by rtfpessoa** [comment]
Sure no problem. Post it here after you finish I can also point to it in the readme as a rust port.

**Comment by enzious** [comment]
@rtfpessoa Alright.

Here's the git: https://github.com/enzious/diff2html
Here's the crates.io page: https://crates.io/crates/diff2html

Right now it's just a cli app for my immediate needs, but I'll work on the library and docs.

Any thoughts on the attribution?

**Comment by rtfpessoa** [comment]
@enzious not really feel free to do as you wish.
