### ISSUE TITLE
single file diff?

### ISSUE THREAD

**Issue by rchancey** [rtfpessoa/diff2html#211]
This is a nice package but is there any way to just have this work against 2 files (strings) ? Or an array of files?

**Comment by ashfp** [comment]
Hi @rchancey -  Just been playing around with this today and I was able to get this to work with 2 strings by using the [npm "diff" package.](https://www.npmjs.com/package/diff).

Example:
```
var stringOne = "string 1 here",
        stringTwo = "string 2 here";

var diffString = JsDiff.createTwoFilesPatch("strings", "strings", stringOne, stringTwo);

var diffHtml = Diff2Html.getPrettyHtml(
          diffString,
          {inputFormat: 'diff', showFiles: false, matching: 'words', outputFormat: 'side-by-side'}
        );

document.getElementById("diff2htmlSideBySide").innerHTML = diffHtml;

```

**Comment by rchancey** [comment]
wow.. Thank you!.. I was researching 'unified diff' last night and wondering when something a simple as a diff got so complicated :) .. will give this a shot. thank you again.

**Comment by rtfpessoa** [comment]
Sorry for the delay getting back here. Thanks for the answer @ashfp
