### ISSUE TITLE
Using Node API, not pretty at all

### ISSUE THREAD

**Issue by mikabytes** [rtfpessoa/diff2html#219]
### Step 0: Describe your environment

  * OS: _____ Ubuntu
  * diff2html version: _____ Latest
  * Using diff2html directly or using diff2html-ui helper: _____diff2html directly
  * Extra flags: _____

### Step 1: Describe the problem:
I'm generating HTML as per the instructions. I am not using UI Helper, there's no documentation describing what that is for, except "Simple wrapper to ease simple tasks in the browser such as: code highlight and js effects"

I don't need code highlight or JS effects.

I'm assuming there's some CSS needed? It would be splendid if instructions for that was included in the docs.

#### Observed Results:
![image](https://user-images.githubusercontent.com/1054229/58118230-b630b380-7c00-11e9-8d71-7d9dca6a6103.png)

#### Expected Results:

I wanted a pretty diff, as can be observed on https://diff2html.xyz/index.htmlhttps://diff2html.xyz/demo.html?diff=https://github.com/rtfpessoa/diff2html/pull/106

#### Relevant Code:

```
      const html = Diff2Html.getPrettyHtml(diff, {
        inputFormat: 'diff',
        showFiles: false,
        matching: 'lines',
        outputFormat: 'side-by-side'
      })
```

**Comment by rtfpessoa** [comment]
In https://github.com/rtfpessoa/diff2html#browser-library you can see the CSSs needed to render the HTML. Are you missing those?

You can use the ones in https://cdnjs.com/libraries/diff2html

**Comment by mikabytes** [comment]
Oh, that's better. I thought that section was for in-browser use only. I was following the Node section, because this is being rendered on server.

![image](https://user-images.githubusercontent.com/1054229/58187860-e6875900-7cb7-11e9-98dd-f9e2df604dec.png)

**Comment by rtfpessoa** [comment]
@mikabytes will try to make it more explicit in the README. thanks for the feedback.
