### ISSUE TITLE
git diff parsing error when text starts with "-"

### ISSUE THREAD

**Issue by codingtwinky** [rtfpessoa/diff2html#22]
Example data

```
diff --git a/coverage.init b/coverage.init
index fc56817..e8e7e49 100644
--- a/coverage.init
+++ b/coverage.init
@@ -19,7 +19,7 @@
 -opt "\-nostart"
 
 # skip stopenv
--do "runbvt,stopenv,getlogs,pullcoveragedata"
+-do "runbvt,getlogs,pullcoveragedata"
 
 ##########################################
 # logs files to bring back to base
```

**Comment by rtfpessoa** [comment]
@codingtwinky , what version are you using? I cannot replicate the problem.
Just updated the examples with your snippet. Check it out here: http://rtfpessoa.xyz/diff2html/

**Comment by codingtwinky** [comment]
You are right, this is what happens when you have too many dev branches that has been diverged too long and didn't bump deps.
