### ISSUE TITLE
Out of memory error sometimes when matching words

### ISSUE THREAD

**Issue by rarkins** [rtfpessoa/diff2html#220]
**Describe the bug**

The `getPrettyHtml` function runs out of memory on certain diffs when matching words. The one I found by accident is only 1000 lines long and about 100kb size.

**To Reproduce**
1. Use this diff: https://gist.github.com/rarkins/4e39a43c92c9ca698310392e82951a95
2. Run `getPrettyHtml` with `matching: 'words'`

I suspect it's because of the minified file compare.

**Expected behavior**
A HTML diff is returned

**Additional context**

Happens both in Chrome as well as Node.js 10 on OSX.

**Comment by rtfpessoa** [comment]
Please check https://github.com/rtfpessoa/diff2html/issues/117#issuecomment-262089378 or any of the other options in https://github.com/rtfpessoa/diff2html#configuration.
It is hard to go for that type of files. If you have any suggestions that we can apply let me know.

**Comment by rarkins** [comment]
I think it’s a pity to close this unresolved. 100kb doesn’t seem large and this explodes the browser with no ability to try/catch, meaning the only option is to greatly reduce the output value permanently. Do you have any learnings from production use, apart from disabling functionality?

**Comment by rtfpessoa** [comment]
I can re-open this but I would like to have any actionable idea here.
Like I mentioned above this is very probably related with the matching algorithm, since that was historically always the cause.

`escitalopram` already improved it a bit in the link above, but unless you have any suggestions I am not sure we will be able to have anything here.

The problem is usually related to the size of the lines, as explained here https://github.com/rtfpessoa/diff2html/issues/67#issuecomment-209848261

Did you try changing this value?

**Comment by rarkins** [comment]
Is there anything that either the algorithm itself can do, or the caller of the algorithm can do, to predict if there will be a problem?

My experience is this:
- Certain files cause the algorithm to blow up the browser
- So, I need to disable word matching permanently

I'd like something in-between where word matching can be done "if possible". The problem was the inability to try/catch and recover in such scenarios.

BTW, I did not directly link my topic to previous ones you have linked to because:
- One of them was about large files, e.g. 13MB, and my example was just 100kb
- `escitalopram` mentioned "The problem seems to be triggered by large blocks of changes, like OASIS.csproj having 2,2k lines added and removed in one block." and this also doesn't describe my problem at all - there's only 1000 lines total, and not all are added/removed

I suspect I can achieve better results - maybe even acceptable ones - if I tweak parameters, but it still seems risky.

**Comment by rtfpessoa** [comment]
Why reducing the size of the blocks for comparison is not enough for you?
I really have no idea what else you can do, I only can see to solutions:
* Change the maximum block comparisons value?
* Improve the resource efficiency of the algorithm?

The first one you need to test, and if it does not work we can maybe try to work with other parts of the size, but the second seems much less achievable rn.

Do you have any new info?

**Comment by rarkins** [comment]
What I really need to avoid is that the browser blows up and kills the page because it hits a memory limit (e.g. 2GB). I can always handle code that throws exceptions that can be caught and recovered from, but this is a case that is unrecoverable. I guess what makes it toughest is that the browser is essentially crashing out rather than the code, and I don't know if the code can be made "aware" that it's likely to trigger a crash.

Unless I can feel confident of reducing crashes to 0.01% of cases then it makes me concerned with using word comparisons in production.

If 2500 is the default, what is a much lower value that you think would still satisfy users in the majority of cases? e.g. can it be something far lower like 100 and still be useful most of the time?

**Comment by rtfpessoa** [comment]
Closed automatically by GH because of my mistaken commit.

**Comment by rtfpessoa** [comment]
Released as version `2.10.0` let me know if you need anything else.
