### ISSUE TITLE
How to use it when get diff info from git diff command

### ISSUE THREAD

**Issue by sunmoondeer** [rtfpessoa/diff2html#221]
HI, I  am sorry I cannt understand how to use diff2html。For Example,  I can get the diff info from git command "git diff commitid1 commitid2" or throught the Jgit APi, then How to  transfor the diff info to html file with diff2html? Can you explain it for me? Thanks a lot

**Comment by rtfpessoa** [comment]
The readme has a full section about usages with examples. What don't you understand?

You just need to pass it in place of `<Unified Diff String>` to the method `Diff2Html.getPrettyHtml`.

Note: When you ask a question in a project in the future please try to provide more details and read the docs first. It is quite impossible to provide much help from my side with this information you provided here.

**Comment by sunmoondeer** [comment]
Got it. It works for me. OW, amazing
