### ISSUE TITLE
Typscript definition file

### ISSUE THREAD

**Issue by mikij** [rtfpessoa/diff2html#223]
I see Typescript definition file does not cover all possible options mentioned in documentation? Is there any particular reason why some options missing like templates and rawTemplates from this file?

**Comment by rtfpessoa** [comment]
@mikij that is probably just my fault. I need to find a better way to avoid divergence.
Any suggestions are welcome.

**Comment by rtfpessoa** [comment]
Extra: Also what matters is the file in the official types repo this is just for reference.

**Comment by rtfpessoa** [comment]
Also updating here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36629
