### ISSUE TITLE
Html. getPrettyHtml diff. Not a valid diff.

### ISSUE THREAD

**Issue by IllegalNick** [rtfpessoa/diff2html#224]
I recerve diff from \SebastianBergmann\Diff, something like:

```
--- updated_at	Jul 1, 2019, 10:24:43 AM
+++ updated_at	Jul 1, 2019, 10:24:43 AM
@@ -1 +1 @@
-<!DOCTYPE html><html lang="en-US"><head><link type="image/png" href="/favicon.ico.png" rel="shortcut icon">
\ No newline at end of file
+<!DOCTYPE html><html lang="en-US1"><head><link type="image/png" href="/favicon.ico.png" rel="shortcut icon">
\ No newline at end of file
```

On my page I run next javascript:

```
var diffHtml = Diff2Html.getPrettyHtml(
            $("#js-diff").html(), 
            {
               inputFormat: "diff", 
               showFiles: false, 
               matching: "lines",
               outputFormat: "side-by-side",               
             }
         );
$("#js-diff").html(diffHtml);
```
Result does not include <!DOCTYPE html><html lang="en-US1">, like on picture.

[https://cdn1.imggmi.com/uploads/2019/7/2/ab9e4f43ead8c385a1d74c4917abe4cd-full.png](https://cdn1.imggmi.com/uploads/2019/7/2/ab9e4f43ead8c385a1d74c4917abe4cd-full.png)

**Comment by rtfpessoa** [comment]
Your question is why it says it is not a valid diff?

From your input I can see at least of immediate problem.
After the chunk start (`@@`) all the lines must start with one of `-`, `+`, ` `.
In your case it starts with `\`.

Maybe you broke it while pasting? But you need to really pass the diff as it is generated.
