### ISSUE TITLE
Remove diff header

### ISSUE THREAD

**Issue by bsrunnels** [rtfpessoa/diff2html#225]
Is there a way to remove the "Diff to HTML by rtfpessoa" header in the diff? I could not find a way to do it from the documentation.

**Comment by rtfpessoa** [comment]
I believe you are referring to the output of the node/npm CLI https://github.com/rtfpessoa/diff2html-cli and not this repo, is this right?

If yes, there is no way to do it unless you use this library manually.
But if you feel that is a problem I would accept a PR to hide that part with an option under the CLI.

Closing for now, let me know if this makes sense.

**Comment by bsrunnels** [comment]
Great, thanks!
