### ISSUE TITLE
I get an ERROR in ./node_modules/diff2html/src/hoganjs-utils.js

### ISSUE THREAD

**Issue by i6448038** [rtfpessoa/diff2html#227]
**Describe the bug**

ERROR in ./node_modules/diff2html/src/hoganjs-utils.js
Module not found: Error: Can't resolve 'path' in '/Users/xxx/Code/projectname/node_modules/diff2html/src'

**To Reproduce**
1. npm install diff2html
2. 
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { _HttpClient, ModalHelper } from '@delon/theme';
import { STColumn, STComponent } from '@delon/abc';
import { SFSchema } from '@delon/form';
import {Diff2Html} from 'diff2html'

@Component({
  selector: 'app-switch-config',
  templateUrl: './config.component.html',
})
export class SwitchConfigComponent implements OnInit {
  outputHtml = '';

  constructor(private http: _HttpClient, private modal: ModalHelper) { this.init()}

  ngOnInit() { }



  init() {
    let strInput = "--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n";
    let outputHtml = Diff2Html.getPrettyHtml(strInput, {inputFormat: 'diff', showFiles: true, matching: 'lines'});
    this.outputHtml = outputHtml;
  }

}
```
3. 
```<page-header>
</page-header>
<nz-card>
  <div [innerHtml]="outputHtml"></div>
</nz-card>
```
4. run and See error

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [Chrome]

**Additional context**

**Comment by rtfpessoa** [comment]
Hi @i6448038, I am not sure I have any idea what can be wrong here. Seems like you have an issue with the path module. It should come by default with node.
If you are using this on the browser you need to use the browser distribution (directory `dist`) and not the one directly from node (directory `src`).

**Comment by farlock85** [comment]
@rtfpessoa I'm getting the same error. I believe `path` is not a standard package (at least on Windows), I think the simplest solution is to just include `path` to the package.json.

**Comment by i6448038** [comment]
@farlock85 @rtfpessoa I have already solved this problem. I just add the ``path`` module with ``npm install path`` and it worked!

**Comment by rtfpessoa** [comment]
@i6448038 thanks for the help.
I will try to review the deps and maybe fix this.
@farlock85 For now please use the suggestion by @i6448038.

**Comment by kalahari** [comment]
In order to get @i6448038's work-around to build/run, I had to add this to my `polyfills.ts` under Angular 8.
```typescript
// allow path module to load
(window as any).process = {};
```

**Comment by rtfpessoa** [comment]
@i6448038 after a bit more of investigation I just remembered this is being solved in the result available in the dist directory. If you import that one for the browser it will work as expected,
