### ISSUE TITLE
How to show diff of more than 1 commit?

### ISSUE THREAD

**Issue by marataziat** [rtfpessoa/diff2html#231]
### Step 1: Describe the problem:
How can I put two or more commits into diff2html? ['https://github.com/OTRS/otrs/commit/0680603a07b8dc37c2ddca6ff14e0236babefc82', 'https://github.com/OTRS/otrs/commit/2997b36a7c84e933c4b025930cabe93efc4d261d', 'https://github.com/OTRS/otrs/commit/c4ec9205bde9c49770ddad94c1a980c006164949']

I know that I can get diff via https://github.com/OTRS/otrs/commit/0680603a07b8dc37c2ddca6ff14e0236babefc82.diff but how to split them without file copying? Sometimes when you have two files changed like here: https://github.com/OTRS/otrs/commit/0680603a07b8dc37c2ddca6ff14e0236babefc82 and https://github.com/OTRS/otrs/commit/2997b36a7c84e933c4b025930cabe93efc4d261d you will get duplicate of CHANGES.md :( How to fix file duplicating / or how to properly render more than 1 commits?

**Comment by rtfpessoa** [comment]
diff2html does not support support multiple diffs.
Actually in don't even see a way to combine diffs that would be doable and
made sense, specially since you need context.

If what you are talking about is to do a diff between multiple commits you
can do that with git and then pass it to diff2html.

e.g.: `git diff HEAD~4`
-- 
Best Regards,
Rodrigo Fernandes

**Comment by marataziat** [comment]
How can I show more than 1 commit? I'm working on CVE browser, which will show users source code of vulnerable applications! And some CVE's have multiple git commit references which I need to render! so is this possible to render more than 1 git commit?

**Comment by rtfpessoa** [comment]
@marataziat I am not sure how I can explain this better.
But if you just have completely unrelated commits I don't see a way to show them as one.

What you can try is just append the contents  of the several diffs and see the result (should work ok in theory), but if you have files with the same name seems quite impossible to merge them. You will end up with the names repeated.
