### ISSUE TITLE
Binary file diff show previous file diff and all added/deleted files showed as RENAMED label in header

### ISSUE THREAD

**Issue by charlieviolet** [rtfpessoa/diff2html#233]
**Describe the bug**
Sorry to bother you.

actually, i use latest release version 2.11.2 in react js. 

the diff string passed into getPrettyHtml function and get the html output as expected.

but unfortunately, there were 2 tricky things :

1. acting like https://github.com/rtfpessoa/diff2html/issues/119, binary files have displyed diff-content of other files (maybe previous plain file)

2. all new added/deleted files have the 'RENAMED' label in header of diff block with the html code like :<span><d2h-changed-tag>RENAMED</d2h-changed-tag></span>

**Comment by rtfpessoa** [comment]
Can you provide the simplest example for me to replicate this in a test?

**Comment by rtfpessoa** [comment]
@charlieviolet let me know if you are able to provide some example to replicate and we can then re-open.
