### ISSUE TITLE
*Bug* Rendering "-->" in text as deleted indicator

### ISSUE THREAD

**Issue by unmem** [rtfpessoa/diff2html#234]
**Describe the bug**
It should not be consider a deleted text.

**To Reproduce**
1. ```diff -u <(echo "First\nSecond") <(echo "First\n-->Second\nThird") | diff2html -i stdin```
2. ```diff -u <(echo "First\nSecond") <(echo "First\n-->Second\nThird") | pbcopy``` and paste it to [diffy.org](https://diffy.org)

**Expected behavior**
It rendered WRONG as:
<img width="417" alt="Screen Shot 2019-09-08 at 12 47 27 AM" src="https://user-images.githubusercontent.com/16096559/64477804-76530380-d1d2-11e9-9227-01b9ff1417ab.png">
and SHOULD BE:
<img width="383" alt="Screen Shot 2019-09-08 at 12 47 33 AM" src="https://user-images.githubusercontent.com/16096559/64477806-78b55d80-d1d2-11e9-95d9-5155a2aecd95.png">

Compared with:
```diff -u <(echo "First\nSecond") <(echo "First\n*Second*\nThird") | diff2html -i stdin```
<img width="405" alt="Screen Shot 2019-09-08 at 12 50 50 AM" src="https://user-images.githubusercontent.com/16096559/64477877-1ad54580-d1d3-11e9-9fa5-66a56199ecfd.png">

**Comment by rtfpessoa** [comment]
Thanks for the detailed explanation and examples. I will try to take a look when I get some time.

If you are able to check it yourself a PR is always welcome.

**Comment by rtfpessoa** [comment]
Please check https://github.com/rtfpessoa/diff2html-cli/pull/54 for more information.
