### ISSUE TITLE
The report result is opposite

### ISSUE THREAD

**Issue by sunmoondeer** [rtfpessoa/diff2html#235]
**Describe the bug**
The report result is opposite

version:
# diff2html -v
3.0.4

![error](https://user-images.githubusercontent.com/9718565/65132614-d0a25e80-da33-11e9-85fe-1ba4502aada3.jpg)

**Comment by rtfpessoa** [comment]
@sunmoondeer how did you generate the diff?
I think you just generated the opposite direction of the diff, just invert the order and it should be fine.

**Comment by sunmoondeer** [comment]
I used command git diff branchA master >>info.diff,   git diff master branchA >> info.diff

diff2html -s side -F 4.html -f html -i file info.diff  

The result still is opposite. What am i wrong?

**Comment by rtfpessoa** [comment]
You should be using `git diff master branchA | diff2html -i stdin -s side -F 4.html -f html` to check what changes are in branchA that are not yet in master.

I just tested with the latest version and it only fails if you change the order and use the wrong one `git diff branchA master`

**Comment by sunmoondeer** [comment]
fixed. Thanks a lot
