### ISSUE TITLE
Render html also for identical files

### ISSUE THREAD

**Issue by ruohomaa** [rtfpessoa/diff2html#245]
Is it possible to render the html also in cases where the files are identical ? There could be a separate option for this.
I have a case where I compare 2 files from different systems and in cases where these are identical it would be nice to show them side-by-side (and the type of change would be identical)
Similar to how Beyond Compare is showing he changes.

**Comment by rtfpessoa** [comment]
@ruohomaa not sure I completely get your idea.
Still, if what you want is for Diff2Html to show files that don't change that is quite out of scope here.
Diff2html just parses and generates pretty html from a diff, if the information was never in a diff there is not much we can do.
If you find a way for the diff to have that information we should be able to show it.
Does it make sense?

**Comment by ruohomaa** [comment]
Thanks for answering,
I realize that it is a bit out of scope since the unified diff file does not actually contain anything if the files are identical
My use case is a bit like Beyond Compare app with which you can compare 2 files side-by-side (in the case when the files are identical it still shows the content of the files)
I need to come up with some other solution
Thanks

**Comment by rtfpessoa** [comment]
I guess you could try to increase the number of context lines (which defaults to 3 in git) to a big number like 1000 and maybe that way you might get it.
Closing this since we cannot do much on this side. Let me know if I can help with anything else.
