### ISSUE TITLE
Can I use diff2html with already compared HTML?

### ISSUE THREAD

**Issue by vickyrathee** [rtfpessoa/diff2html#249]
I am using a server side comparison script which generate the difference HTML. Can I use the diff2html to show that generated HTML?

- I don't have 2nd file, and no comparison needed using diff2html 
- Just need to show the HTML with green/red highlighted as per `ins` and `del`  in my html string

```
var html = "<html><head></head><body>18,626,<del class=\"change\">207</del><ins class=\"change\">226</ins>\n\nquestions        </body></html>";
var diffHtml = Diff2Html.getPrettyHtml(
  html, {inputFormat: 'diff', showFiles: true, matching: 'lines', outputFormat: 'side-by-side'}
);
document.getElementById("diffResult").innerHTML = diffHtml ;
```

**Comment by rtfpessoa** [comment]
@vickyrathee this is a tool to parse diffs and generate html from it.
To show your html you just need to use an HTML file and some css. You can check the css here for examples https://github.com/rtfpessoa/diff2html/blob/master/src/ui/css/diff2html.css#L119
