### ISSUE TITLE
Placement of --no-color

### ISSUE THREAD

**Issue by mathiasrw** [rtfpessoa/diff2html#250]
**Describe the bug**
When I want to diff a specific folder from another branch the option `--no-color` is placed after the input and the command breaks. 

**To Reproduce**
1. Execute `diff2html develop 'test/*'`

**Expected behavior**
The same diff as running `git diff develop 'test/*'` is converted to html

**Screenshots**
![image](https://user-images.githubusercontent.com/1063454/70854425-cd483300-1ebb-11ea-81fc-aed985320732.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 4.2.1

**Comment by rtfpessoa** [comment]
@mathiasrw I think you might be referring to https://github.com/rtfpessoa/diff2html-cli right?

**Comment by rtfpessoa** [comment]
@mathiasrw if you need more customization you can always build your own command with `git diff <all-my-arguments-options-and-flags-here> | diff2html -i stdin` and that way you should avoid these type of issues.

Let me know if you need anything else.
