### ISSUE TITLE
dependabot incredibly spammy

### ISSUE THREAD

**Issue by pbu88** [rtfpessoa/diff2html#292]
Hello,

This is not a conventional issue, feel free to close at any time. I just wanted to bring up that the automated emails from dependabot are incredibly spammy for whoever is subscribed to the notifications of this repo.

It's just a feedback. I know I can un-subscribe but I don't want to :-)

Cheers!

PS: Attached is an email on how it looks on my email every time we get a burst of these emails.

![image](https://user-images.githubusercontent.com/3682272/72241547-62d40100-35e7-11ea-8633-f664a7596f66.png)

**Comment by rtfpessoa** [comment]
@pbu88 sorry for the spam. I started testing this as a mean to keep stuff updated.
I completely understand your pain.
I have changed the updates just to security and changes the amount to immediately to reduce the amount at a time.
Let me know if it still bothers you.
