### ISSUE TITLE
Bash diff new file not shown

### ISSUE THREAD

**Issue by pebbles186** [rtfpessoa/diff2html#298]
### Step 0: Describe your environment

- OS: CentOS 7
- diff2html version: 2.12.2
- Using diff2html directly or using diff2html-ui helper: ui helper
- Extra flags: none

#### Steps to reproduce:

1. Create two directories e.g. /test/dir1 and /test/dir2
2. Add a file to /test/dir1
3. Execute via bash "diff --recursive --exclude=".*" --unified /test/dir1 /test/dir2"
4. get the diff string via ajax
5. Execute in application.js:
```
var diff2htmlUi = new Diff2HtmlUI({
        diff: diffString
    });
    diff2htmlUi.draw(selector, {
        inputFormat: 'json',
        showFiles: true,
        outputFormat: 'side-by-side',
        synchronisedScroll: true
    });
```

#### diff example:

```
Only in /test/dir1: newfile.php
```

#### Observed Results:

- No changes are shown.

#### Expected Results:

- The file newfile.php should be shown as added

#### Relevant Code:

```
$retval = null;
$cmd = 'diff --recursive --exclude=".*" --unified /test/dir1 /test/dir2';
ob_start();
system($cmd, $retval);
$data = ob_get_contents();
ob_end_clean();
print_r(json_encode($data));
```

**Comment by rtfpessoa** [comment]
@pebbles186 as detailed here https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html I do not think the `Only ...` are part of a valid unified spec.

In this case by adding `-N` to your command I started getting the expected output.

You can also use `git diff --no-index /test/dir1 /test/dir2` to get a nice output.

Let me know if you have any other questions.

**Comment by pebbles186** [comment]
You are right, was my mistake, thanks for the hint. Now I get the file in the output, but it is always shown as changed.
Here is my diff output, maybe you can check this on your side.
```diff --recursive '--exclude=.*' --unified --unidirectional-new-file liplo/newfile.php liplo/newfile.php
--- liplo/newfile.php	1970-01-01 01:00:00.000000000 +0100
+++ liplo/newfile.php	2020-01-20 08:48:25.376660000 +0100
@@ -0,0 +1,4 @@
+<?php
+/**
+ * Test file, should be shown as new
+ */
```

Or is my assumption wrong and this is not possible with a bash diff output? Unfortunately we do not use git :(

**Comment by rtfpessoa** [comment]
No problem.
I am not sure what is the current issue.

Can you extend a bit better on what you get and what you were expecting?

**Comment by rtfpessoa** [comment]
If you check here https://diffy.org/diff/z2mdvog5ayerlvk5hy2xzuxr the output seems correct. What am I missing?

**Comment by pebbles186** [comment]
Okay, then I am probably wrong. I thout it will show the label added for the new file. As shown here:
[Example with git](https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=10000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=line-by-line&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&smartSelection=1&diff=https://github.com/pebbles186/test123/pull/4)

**Comment by rtfpessoa** [comment]
@pebbles186 since you are not using git I won't detect if it is a new file.
I could infer it from the type of the lines, but that could still be wrong when no context lines are provided.

**Comment by pebbles186** [comment]
@rtfpessoa I understand, thanks for you help.
I am using a workaround now. I detect deleted/added files on myself and add the string which would be added by git. Then your library is working as expected. :)
