### ISSUE TITLE
 error TS2322: Type '"side-by-side"' is not assignable to type 'OutputFormatType'.

### ISSUE THREAD

**Issue by absukumaran** [rtfpessoa/diff2html#299]
I'm using below code in my angular application
const outputHtml = Diff2Html.html(strInput, { drawFileList: false, outputFormat: 'side-by-side'});

While running program. It throws error.
The expected type comes from property 'outputFormat' which is declared here on type 'Diff2HtmlConfig'

**Comment by rtfpessoa** [comment]
@absukumaran that is an interesting question. I think in practice a string should work, but since I defined it as an enumeration to be able to enumerate values it complain if you don't use the enumeration.

Can you try passing `OutputFormatType.SIDE_BY_SIDE`?

**Comment by rtfpessoa** [comment]
@absukumaran I also released version `3.0.0-releasemajorversion.5b2c3ab` without enums and now you should be able to use strings.
Let me know if it works.

Sometimes you might need to cast your string to constant type with `'side-by-side' as const`.

**Comment by absukumaran** [comment]
@rtfpessoa Yes, Now It is working fine.

**Comment by absukumaran** [comment]
@rtfpessoa I have one more issue. Some pull id's diff showing like this. It showing diff wrongly and repeating the same file diff again and again.
![sas](https://user-images.githubusercontent.com/58422135/73542023-d1271900-4459-11ea-880f-0cf19ffd752a.png)

**Comment by rtfpessoa** [comment]
@absukumaran can you provide a sample for me to replicate?

**Comment by absukumaran** [comment]
@rtfpessoa 
[samplediff.txt](https://github.com/rtfpessoa/diff2html/files/4147952/samplediff.txt)

**Comment by rtfpessoa** [comment]
@absukumaran that is not  valid diff. Maybe that is the issue. It contains extra things that are not part of the git diff.
Can you try with just the diff?

**Comment by absukumaran** [comment]
@rtfpessoa But that data, I got from github diff api. I haven't added anything extra.

**Comment by rtfpessoa** [comment]
@absukumaran when you get from github you need to use the url ending in `.diff`, like `https://github.com/rtfpessoa/diff2html/commit/f89c3481a744f2f1e0ddf830f631f59102941f69.diff` not the one ending in `.patch`.

Seems like you are using the patch one.

**Comment by absukumaran** [comment]
@rtfpessoa Yes, your are right. I was using patch file, now I changed to diff file. Now it is working properly. Thanks @rtfpessoa

**Comment by rtfpessoa** [comment]
Np. Maybe I should add this to troubleshooting
