### ISSUE TITLE
word-to-word diff gives wrong escaping (when diffing like HTML files)

### ISSUE THREAD

**Issue by dai-shi** [rtfpessoa/diff2html#3]
Sorry to bother you again, but this is rather a fatal bug.
With the following example:

```
diff --git a/foo.js b/foo.js
---
+++
@@ -1,3 +1,3 @@
 one
-two <h1>word</h1>
+to word
 four
```

we get something like:
```
-two &lt;h1&gt;word&lt;/h1&gt;
```

**Comment by rtfpessoa** [comment]
@dai-shi sorry for the delay but I was really busy.
Today I had some time and I decided to do some fixes.
This is fixed.

**Comment by dai-shi** [comment]
Cool. Thanks.
