### ISSUE TITLE
Render Markdown

### ISSUE THREAD

**Issue by the-turk** [rtfpessoa/diff2html#308]
Is it possible to render markdown in diffs like GitHub edit history does? If not, do you know if there is any way to do this (with another repo maybe)?

Thanks.

**Comment by rtfpessoa** [comment]
@the-turk you provide an example? Not sure what you mean.

**Comment by the-turk** [comment]
Check my edit history **LIKE THIS** OR _THIS_ OR `THAT`

**Comment by rtfpessoa** [comment]
@the-turk that is not possible out of the box. You would have to render the markdown into HTML.
This could probably mess with the char/word diff inside each line.
