### ISSUE TITLE
diff2htmlUi.fileListToggle() is broken.

### ISSUE THREAD

**Issue by yuliy-otonomo** [rtfpessoa/diff2html#309]
Can't make a PR ATM, but:

diff2html-ui-base.ts:83
  `const showBtn: HTMLElement | null = this.targetElement.querySelector('d2h-show');` 

`d2h-show` is missing dot )

**Comment by rtfpessoa** [comment]
Thanks for reporting. Will issue a fix soon.

**Comment by rtfpessoa** [comment]
Will release this soon
