### ISSUE TITLE
[Nice To Have Feature] Support staged diff in git

### ISSUE THREAD

**Issue by rohithbalaji123** [rtfpessoa/diff2html#313]
It would be nice to have a flag which shows diff which are only in git's staging area. Would be helpful in verifying what changes are exactly being committed and have some final fine tunings.

Please do let me know if there is a workaround to attain this with currently supported features.

**Comment by rtfpessoa** [comment]
@rohithbalaji123 diff2html is merely a parser and html generator it cannot decide what changes you have in your machine at any time.

If you are referring to https://github.com/rtfpessoa/diff2html-cli you can always use a custom git diff command like: `git diff HEAD~2 | diff2html -i stdin`

Is this what you are looking for?

**Comment by rohithbalaji123** [comment]
Ohh, yeah. This would be it. I misunderstood the project. Didn't realize giving input source was an option. That's nice. Thanks!
