### ISSUE TITLE
How to specify the diff string to diff against?

### ISSUE THREAD

**Issue by grantspilsbury** [rtfpessoa/diff2html#318]
This is a terribly stupid question...
If I have stringA "This is a stringA" and stringB "This is also a string"
How do I use the library to diff the 2 strings? 
```
const diffJson = Diff2html.parse(stringA);
const diffHtml = Diff2html.html(diffJson, { drawFileList: true });
```
Where do I set stringB as the string to be diffed against?

**Comment by rtfpessoa** [comment]
@grantspilsbury the is not a diff generator library, it is a parser for existing unified diffs.
You can use any tool that generates unified diffs  and than pass that input to diff2html to get either the parsed version or the pretty html.

You can use, gnu diff, git diff, or any other language specific tool you want, as long as it outputs the unified syntax.
