### ISSUE TITLE
typescript example can't be compiled

### ISSUE THREAD

**Issue by Trim21** [rtfpessoa/diff2html#320]
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: **windows**
- diff2html version: **3.1.6**
- Using diff2html directly or using diff2html-ui helper: **directly **
- Extra flags: **null**

### Step 1: Describe the problem:

I try to use `diff2html` in typescript way like [readme#typescript](https://github.com/rtfpessoa/diff2html#diff2html-angular-example) but I found I can't compile it.

#### Steps to reproduce:
install `diff2html`, `typescript`, `@types/diff2html==0.0.5`
```ts
import * as Diff2Html from 'diff2html'

export function render (diff: string) {
  return Diff2Html.html(diff)
}
```

compile:

```
./node_modules/.bin/tsc
src/js/ui.ts(5,20): error TS2339: Property 'html' does not exist on type '{ Diff2Html: Diff2Html; }'.
```

#### Observed Results:

It works with ` // @ts-ignore`, so I guess it's not a bug of source but typedefinition

should be compiled correctly

**Comment by rtfpessoa** [comment]
@Trim21 you should not need `@types/diff2html` anymore. That was used when the code was JS.
Not that it is TS the types ship with the code.

That should be the reason why `function html` is not available, since it was introduced in the redesign of the migration to TS.

**Comment by Trim21** [comment]
Thank you
