### ISSUE TITLE
Issue with HTML Comparisons

### ISSUE THREAD

**Issue by Parker29** [rtfpessoa/diff2html#321]
While comparing HTML files,
 < > get replaced automarically while rendering the output on browser.
I think its a bug but still not fixed.
![Screenshot from 2020-04-29 13-57-39](https://user-images.githubusercontent.com/28523227/80576084-3622e880-8a22-11ea-8891-b6d004679ea3.jpg)

![Screenshot from 2020-04-29 13-54-59](https://user-images.githubusercontent.com/28523227/80576081-34592500-8a22-11ea-946d-ba7da44f81c5.jpg)

**Comment by rtfpessoa** [comment]
@Parker29 unless you provide an example diff I cannot replicate.

See https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=10000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=line-by-line&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&smartSelection=1&diff=https://github.com/h5bp/html5-boilerplate/commit/c6b5f62d58d5e206ea77cad115bc755a31b637b2.diff

**Comment by Parker29** [comment]
Thank you for the reference.
The issue was with the options from my end.
