### ISSUE TITLE
Better diff files order

### ISSUE THREAD

**Issue by rtfpessoa** [rtfpessoa/diff2html#33]
* New files should be in the end of the diff (before deleted)
* Deleted files should be in the end of the diff

**Comment by pbu88** [comment]
Hi, I can't understand what's the issue here

**Comment by rtfpessoa** [comment]
@pbu88 it is not an issue. It is just an improvement. Most times when I am reviewing prs with lot of deletes. They usually do not matter much compared to changed files.

The idea would be to order the diff in a way where the removed files would be in the end.
Do you agree?

**Comment by pbu88** [comment]
Hmmm, normally deleted files don't show in the diff. I always have to include them by staging them (git add) and then doing git diff --cached. Then they show up all in red.

I agree is super useful to see the added/deleted files but don't know how to make them appear without doing some tricks from the terminal with git.

**Comment by rtfpessoa** [comment]
Usually if you do a commit where you delete, add or move files, with `git diff -M HEAD~1'` you can see all the changes.

**Comment by rtfpessoa** [comment]
Doesn't seem much relevant today.
