### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by madooei** [rtfpessoa/diff2html#331]
I'm putting this as a general observation of an issue - which is a serious one in my view - your CSS in some places uses relative and other places absolute units. There is also an inherent coupling on default (browser) styling of e.g. tables. If one uses a custom styling for their web pages to e.g. style tables in a particular fashion, the diff2html's look will be messed up.

**Comment by rtfpessoa** [comment]
@madooei CSS here is specially hammered in several places due to the lack of knowledge about how to structure it properly.
Several features here were hard to put together and lead to some mess.

If you are interested in making a PR (or multiple) I am completly open to help you making it better.

**Comment by rtfpessoa** [comment]
@madooei if you want to re-open this let me know.
