### ISSUE TITLE
buggy char diffStyle?

### ISSUE THREAD

**Issue by etimau** [rtfpessoa/diff2html#335]
Hi and thanks for your great work.
Here is my issue. Sorry if it is irrelevant or already opened.

### Step 0: Describe your environment
- OS: Windows 10 (1909 18363.959 ; french)
- diff2html version: 3.1.12
- Usage:
	var diffHtml = Diff2Html.html(atob(patch), {
  						drawFileList: false,
  						matching: 'lines',
  						outputFormat: 'line-by-line',
  						diffStyle: 'char',
					});

### Step 1: Describe the problem:
Sometimes (often), the char changes between lines are not correctly highlighted.

#### diff example:
```diff
@@ -2858 +2864 @@
-XXXXXXXXXXXXXXXXXXX00101092020                    118501000100311             10350502610965  9500488486                                     00000                               AF
+XXXXXXXXXXXXXXXXXXX00101092020                    118501000100311             10350502610509259500488486                                     00000                               AF   2
```

#### Observed Results:
See partial screenshot below:
![Char_bad](https://user-images.githubusercontent.com/319380/91182056-f75c2100-e6e9-11ea-9428-c0a848fbcf80.png)

I would have expected:
- The 9 above the 5 to be red highlighted.
- The 5 on the first line, between 6 and space to be red highlighted.
- The 9 on the second line, between 0 and 2 to be green highlighted.
- The 5 below space to be green highlighted.

#### Expected Results:
See partial screenshot below:
![Char_expected](https://user-images.githubusercontent.com/319380/91182103-0511a680-e6ea-11ea-95c9-5f9c7f48363e.png)

**Comment by rtfpessoa** [comment]
Hi @etimau,

If I understood it correctly it seems like a feature not a bug.
I rely on [diif](https://www.npmjs.com/package/diff#api) to detect the differences and I use `diffChars` and `diffWordsWithSpace` that you can select in the options.

Not sure if [diif](https://www.npmjs.com/package/diff#api) supports the exact feature you want but if there is a method I can call there let me know.

**Comment by rtfpessoa** [comment]
@etimau let me know if you want to re-open this.
