### ISSUE TITLE
Source Code of diff2html demo

### ISSUE THREAD

**Issue by BingyuLiu** [rtfpessoa/diff2html#338]
Can you please share the source code of demo https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=10000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=line-by-line&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&smartSelection=1&diff=https://github.com/rtfpessoa/diff2html/pull/106

**Comment by Kitefr** [comment]
Maybe this is the one : https://github.com/rtfpessoa/diff2html/tree/master/website/templates/pages/demo

**Comment by rtfpessoa** [comment]
Sorry for the delay, @Kitefr thanks for posting the link.

**Comment by rtfpessoa** [comment]
@BingyuLiu let me know if you want to re-open this.
