### ISSUE TITLE
Is possible JSON Diff similar a http://www.jsondiff.com/?

### ISSUE THREAD

**Issue by pacocom** [rtfpessoa/diff2html#339]
Is possible JSON Diff similar a http://www.jsondiff.com/?
![image](https://user-images.githubusercontent.com/7735329/95429808-2dc4c700-094b-11eb-8af9-7099d10aea2d.png)

Thanks!

**Comment by rtfpessoa** [comment]
Hi @pacocom, diff2html is a diffparser and html generator, which means it does not generate diffs.
But if you pass a diff of two json objects it will generate a similar view.

You can try using [jq](https://stedolan.github.io/jq/) to format the contents before doing to diff so it looks better formated.
