### ISSUE TITLE
Changed tag is displayed despite both files being the same

### ISSUE THREAD

**Issue by imranazad** [rtfpessoa/diff2html#342]
### Step 0: Describe your environment

- OS: Windows 10 
- diff2html version: 3.1.13
- Using diff2html directly or using diff2html-ui helper: diff2html 

### Step 1: Describe the problem:
Changed tag is displayed despite both files being the same.

#### diff example:

```diff
Index: new/test.html\n===================================================================\n--- new/test.html\n+++ new/test.html\n
```

#### Observed Results:

I have to files with the words `hello` in them when the html diff is generated the changed tag is displayed even though it says `File without changes`

#### Expected Results:

I expected the changed tag not to appear

**Comment by rtfpessoa** [comment]
@imranazad diff2html is mostly a parser for diffs, which means that it does not make any special assumptions about them.
In this case the tool you use to generate the diff should only select the files which have changes.
At least this is the case for most tools I have seen like git.

Let me know if you have more questions.
