### ISSUE TITLE
Where can I find the changelog with changes in between releases?

### ISSUE THREAD

**Issue by mensfeld** [rtfpessoa/diff2html#343]
Hey there. First of all, thank you for this amazing library.

Where can I find the changelog with information about changes in between particular versions? I'm really interested in bug fixes and improvements and would love to be able to keep up with all the changes.

**Comment by rtfpessoa** [comment]
Hi @mensfeld I try to keep the releases updated with relevant information here https://github.com/rtfpessoa/diff2html/releases
But since it is manual I end out forgetting some times. 
At least every release is tagged and you can always check the commit messages.

**Comment by mensfeld** [comment]
Thank you. I was looking for something like a changelog file but this lgtm :) :pray:
