### ISSUE TITLE
Deviated style

### ISSUE THREAD

**Issue by Liang813** [rtfpessoa/diff2html#354]
When I use the code in Diff2Html Browser ，I find something wrong with the style , I don't know what the problem is.
This is the example
![image](https://user-images.githubusercontent.com/62755766/103337396-2af2f180-4ab6-11eb-8e69-38fb9a62ee3e.png)

My code 
<script>
document.addEventListener('DOMContentLoaded', () => {
        var diffHtml = window.Diff2Html.html(diffInfo, {
            drawFileList: true,
            matching: 'lines',
            outputFormat: 'side-by-side',
        });
        document.getElementById('destination-elem-id').innerHTML = diffHtml;
    });
<script>

**Comment by rtfpessoa** [comment]
Weird, can you provided a full example that I can use to replicate the problem?

**Comment by Liang813** [comment]
There was no problem on my other computer, it was probably a browser zoom problem.
