### ISSUE TITLE
Question - Merge Capability

### ISSUE THREAD

**Issue by mohsenomidi** [rtfpessoa/diff2html#361]
Dear Contributors, 

thanks for the library, i want to know is there any merge capability for the diff viewer ? 
like araxis merge ? if there is a diff in side by side view the user can send the line form one side to another ? or is there any workaround solution to do this ?

Regards.

**Comment by rtfpessoa** [comment]
Hi @mohsenomidi,

This tool is a parser and html generator which works on the base of a static input from a valid unified diff.
It does not generate patches and does not parse diffs with conflicts.

Also it seems very outside of the scope here.
