### ISSUE TITLE
What's a DiffFile?

### ISSUE THREAD

**Issue by davidnewcomb** [rtfpessoa/diff2html#362]
In section: https://github.com/rtfpessoa/diff2html#diff2html-api you mention `DiffFile[]` but it isn't mentioned anywhere else.
Please can you add a few words to the documentation describing the type, what it is for and why you might use it instead a plain string.

**Comment by rtfpessoa** [comment]
Hi @davidnewcomb,

> In section: https://github.com/rtfpessoa/diff2html#diff2html-api you mention DiffFile[] but it isn't mentioned anywhere else

You can check all the types here https://github.com/rtfpessoa/diff2html/blob/master/src/types.ts#L49

> What it is for and why you might use it instead a plain string

I cannot see many usages of it from the outside.
The purpose is for you to be able to run `parse` and then invoke the `html` after with the output of parse.
This way you can manipulate/use the json/objects and then render the HTML whenever you need.

**Comment by davidnewcomb** [comment]
Thanks
