### ISSUE TITLE
File content toggle (checkbox) should not be rendered when using `Diff2Html` only

### ISSUE THREAD

**Issue by Pierrci** [rtfpessoa/diff2html#364]
### Step 0: Describe your environment

- OS: **MacOS**
- diff2html version: **3.2.0**
- Using diff2html directly or using diff2html-ui helper: **diff2html**
- Extra flags: **\_**

#### Steps to reproduce:

1. Call `Diff2html.html` on any diff

#### Observed Results:

- A checkbox to toggle the content of the diff is rendered for each file

#### Expected Results:

- When using `Diff2Html` only, there is no JS to listen to events and to update the view when the checkbox is clicked. Thus, it should rather behave the same way as the `fileListToggle` option of `Diff2HtmlUI` for example, and not render the checkbox at all.

**Comment by rtfpessoa** [comment]
Released in https://github.com/rtfpessoa/diff2html/releases/tag/3.3.0
