### ISSUE TITLE
Improve sample page

### ISSUE THREAD

**Issue by rtfpessoa** [rtfpessoa/diff2html#37]
* Allow to see different option combinations (ex: matching lines, without files summary, ... )
* Add some design to the page :smile:

**Comment by mrfyda** [comment]
Any thoughts to get started on this?
What would be the focus of the page? Downloading, contributing, getting started, donating?

I'd like to suggest something like https://docs.readthedocs.org/en/latest/index.html for a comprehensive description of all the option combinations.

**Comment by rtfpessoa** [comment]
I think something like [readthedocs](https://docs.readthedocs.org/en/latest/index.html) is to much for this.
We do not have that much of customization and a simple docs page is enough.

I am looking for something more like a pretty initial page with some sub-pages:

* Example of the tool output
* Feartures highlight
* Configuration parameters
* How to contribute and current list contributors
* Usages (lib in the browser, cli for node, diffy.org, ungit, etc)

My goal was just to improve SEO and have a more appealing image 😄
