### ISSUE TITLE
Feature Request: Template documentation

### ISSUE THREAD

**Issue by Jakobud** [rtfpessoa/diff2html#372]
I'm trying to figure out how the templating system works. Is Mustache required? Or can they just be HTML?

Just glancing at your src/templates I see a lot of various code-replace snippets in there. Where is the documentation for those? What do they do? How do you use them?

Regarding the two template options, it says you pass an "object of templates" to it. What does that mean? What does that object structure look like? Why would you pass more than 1 template into this object? To render multiple output files? Are these templates in this object in string form or is it a string path to the template in the filesystem?

Just really confused on this topic. I've been messing with it without much success. No documentation on it at all that I see.

**Comment by rtfpessoa** [comment]
> Is Mustache required? Or can they just be HTML?
These are the templates that will be passed the parts of the diff for them to render. If they were just HTML they would be static.

> Just glancing at your src/templates I see a lot of various code-replace snippets in there.

Those are the templates. The file name is the name and their contents are the default contents.

> Where is the documentation for those? What do they do? How do you use them?

What type of documentation are you looking for? They are +- simple. It is just a mustache file that receives some input.
It is just an advanced use case if you want to modify the final generated HTML, you just need to pass the name and a different content.

> Regarding the two template options, it says you pass an "object of templates" to it. What does that mean? What does that object structure look like?

It is just a key value with the name of the template and the contents. The raw templates receive the contents in string format while the others you need to compile them with hogan.js

> Why would you pass more than 1 template into this object?

To modify different parts. Each template if for a part of the HTML of the diff

> To render multiple output files? Are these templates in this object in string form or is it a string path to the template in the filesystem?

Already answered in previous points

What exactly are you trying to achieve here?

**Comment by Jakobud** [comment]
Okay thanks. I was looking at the snippets like:

```
{{>fileIcon}}
{{fileHtmlId}}
{{addedLines}}
{{deletedLines}}
{{CSSLineClass.INFO}}
{{contentClass}}
{{{blockHeader}}}
{{type}}
{{prefix}}
{{#content}}
{{^content}}
{{>fileTag}}
etc..
```

Like I'm interested in constructing my own templates but have no clue what all these different tags do. I was just looking for some explanation on what they do so I could structure my templates accordingly. Thanks.

**Comment by rtfpessoa** [comment]
I do not think I could have a good description for those values, I guess I could have an image pointing them out but I have no time right now to do that.

Do you have any specific doubt about those?

If you are interested in contributing descriptions it is very welcome.

**Comment by rtfpessoa** [comment]
Fixed by https://github.com/rtfpessoa/diff2html/pull/384 thanks to @domdomegg
