### ISSUE TITLE
Feature Request for documentation on multi-file diff input format

### ISSUE THREAD

**Issue by Jakobud** [rtfpessoa/diff2html#373]
I have multiple file diffs that I want to input into your tool. How do you format multiple file diffs into a single Unified Diff format? What is the expected format exactly? Just concat them together?

Thanks!

**Comment by rtfpessoa** [comment]
> I have multiple file diffs that I want to input into your tool. How do you format multiple file diffs into a single Unified Diff format? What is the expected format exactly? Just concat them together?

The tool just expects a string with a valid unified diff, you can check the spec here https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html. But I guess that what you want is the concatenation.

Most diffs are multi file, I cannot see what would be special documentation for that. You just need to pass the contents, like you get from a git diff.

**Comment by Jakobud** [comment]
Thanks all I was wondering about is the concatenation. The above GNU.org link does show an example but it's only for a single file. As far as documentation I guess I was just looking for an example diff for multiple files. Thanks for your help! Cool tool.

**Comment by juancrescente** [comment]
+1

**Comment by rtfpessoa** [comment]
I added a new section here https://github.com/rtfpessoa/diff2html/commit/9987e7c69552717f253db760a03bae4de0697f56
Let me know if you would add something else. PRs are welcome.
