### ISSUE TITLE
Document that the order of inclusion of the CSS files matters

### ISSUE THREAD

**Issue by charguer** [rtfpessoa/diff2html#375]
- OS: **Ubuntu**
- diff2html version: **master (084eb40)**
- Using diff2html directly or using diff2html-ui helper: **diff2html-ui **

#### Steps to reproduce:

1. *** Include  diff2html.min.css  before   highlight.js/10.7.1/styles/github.min.css 

#### Observed Results:

- The display has extra vertical blank lines

#### Relevant Code:

I suggest leaving a short note in the README file to point out that the order of the CSS include is important, in the "Syntax Highlight" section.

PS: thanks for a fantastic tool.

**Comment by rtfpessoa** [comment]
Feel free to send a PR
