### ISSUE TITLE
Can diff2html work with --word-diff?

### ISSUE THREAD

**Issue by NL33** [rtfpessoa/diff2html#393]
In my nodejs app, I want to display some diffs from git that are created using `$ git diff --word-diff`, based on [word-diff](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---word-diffltmodegt). This is in order to show the changes word-by-word (character by character), instead of block by block.

Is it possible to use diff2html with `word-diff`, so as to add color highlighting to the diff?

I don't see this addressed in the docs or issues.

**Comment by rtfpessoa** [comment]
Hi @NL33, you can just get a regular diff and than when you invoke diff2html the config `diffStyle` is set to word by default and will generate the differences.

Let me know if you need anything else.

**Comment by NL33** [comment]
Hi. I believe this still shows the diff in (what I am calling, maybe incorrectly) a "block" view, with deletions as a block on top of a block of additions. That is how the default `git diff` works.

Instead of this, running [git diff --word-diff](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---word-diffltmodegt) produces a comparison where changes are "integrated" in the same place--so changes in characters are right next to each other. 

Similar to the "rich diff" view from github (example [here](https://github.com/jlevy/the-art-of-command-line/commit/6f12627e92d68cd89f9bf4b5f12392ac491f8948?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)--the addition is added right in the text).

I'm wondering if it's possible for `diff2html` to display this kind of diff.

**Comment by rtfpessoa** [comment]
I see what you mean. That is unfortunately not supported by diff2html.

**Comment by NL33** [comment]
Thanks, @rtfpessoa. Are you familiar with whether git allows you to customize the addition/subtraction symbols that come back with `--word-diff`? That would at least allow some customization like diff2html often provides.

So, if you run `$ git diff --word-diff,` added text shows up as `{+....+}`. Are you familiar with how to change the `{+ `symbol?

Normally you could do `--output-indicator`, but that doesn't seem to work for `word-diff`.

**Comment by rtfpessoa** [comment]
@NL33 the way diff2html it would never work by changing the git format, since that is the base of the tool.
What you could do would be to not split the lines after we run the line diff internally and that way you could get a similar output. But that would be a bit of work.

**Comment by rtfpessoa** [comment]
Sorry for the delay, but I completely forgot about this issue.

I am referring to this piece of code https://github.com/rtfpessoa/diff2html/blob/master/src/render-utils.ts#L246
where we comprar the new and the old line and then highlight the new and old parts. What you want is the version that does not separate the new and old in two different lines but directly the output of jsdiff.

**Comment by NL33** [comment]
Thanks. I appreciate the info.
