### ISSUE TITLE
我有 diff 内容但使用它转为html片段出错

### ISSUE THREAD

**Issue by guicaiyue** [rtfpessoa/diff2html#394]
`diff --git a/sample.js b/sample.js
      index 0000001..0ddf2ba
      --- a/sample.js
      +++ b/sample.js
      @@ -1 +1 @@
      -console.log("Hello World!")
      +console.log("Hello from Diff2Html!")`;
这个样的内容也会提示 file without changes。我不知道怎么办，因为这个例子是你们提供的
https://www.npmjs.com/package/diff2html

**Comment by guicaiyue** [comment]
我找问题了在字符串通过'\n'切割成数组时，--- @@ - +等符号前面有空格存在，所以失败了。

**Comment by rtfpessoa** [comment]
@guicaiyue Glad you solved it, next time please try to ask in english since I cannot read in other languages except Portuguese/English.
