### ISSUE TITLE
support show unchanged lines

### ISSUE THREAD

**Issue by Kyson** [rtfpessoa/diff2html#406]
support show unchanged lines

like gitlab merge request

![image](https://user-images.githubusercontent.com/3901140/137446606-125708d5-07b5-4638-980c-96f08b1f7380.png)

**Comment by rtfpessoa** [comment]
This is out of context for his project. This project only parses and generates HTML for the diff it receives in has no information to get the rest of the lines. If you want you can generate the original diff with more context. You can check the `-U` flag on `git diff` for example.

**Comment by PrestonTaylor** [comment]
Beyond my abilities and time for now but maybe someone else could pick it up. Add a separate issue for this?
