### ISSUE TITLE
Is there a config to render '\n' which is an empty line.

### ISSUE THREAD

**Issue by ricenoddle** [rtfpessoa/diff2html#421]
Hello there, this is not a bug report but a question

### Step 0: Describe your environment

- diff2html version: **2.12.2**

### Step 1: Describe the problem:

Let's say I have the following diff code in the diff example.

![image](https://user-images.githubusercontent.com/13479751/149894496-b7ce9624-49fd-4f8b-9206-c9d46ce9e133.png)

I set the css style `user-select: none` for not to copy '+' which have a class `d2h-code-line-prefix`. Then I got the problem.

![image](https://user-images.githubusercontent.com/13479751/149894753-4bec7700-dc0f-4f97-9efc-95402ce774d6.png)

So I'm wondering is there a way to render an emptyline or is there a way for not copy `d2h-code-line-prefix`.
#### diff example:

```diff
const diff =
        '--- a/src/html-printer.js\n' +
        '+++ b/src/html-printer.js\n' +
        '@@ -8,6 +8,7 @@ function test {\n' +
        ' (function() {\n' +
        "   var LineByLinePrinter = require('./line-by-line-printer.js').LineByLinePrinter;\n" +
        "   var SideBySidePrinter = require('./side-by-side-printer.js').SideBySidePrinter;\n" +
        "-  var FileListPrinter = require('./file-list-printer.js').FileListPrinter;\n" +
        "+  var FileListPrinter = require('./file-list-printer.js').FileListPrinter2;\n" +
        ' \n' +
        '   function HtmlPrinter() {\n' +
        '   }\n' +
        '@@ -22,5 +23,10 @@\n' +
        '     return sideBySidePrinter.generateSideBySideJsonHtml(diffFiles);\n' +
        '   };\n' +
        ' \n' +
        '+  HtmlPrinter.prototype.generateFileListSummary = function(diffJson, config) {\n' +
        '+    var fileListPrinter = new FileListPrinter(config);\n' +
        '+    return fileListPrinter.generateFileList(diffJson);\n' +
        '+  };\n' +
        '+\n' +     (**Please look at this line**)
        '   module.exports.HtmlPrinter = new HtmlPrinter();\n' +
        ' })();\n';
```

**Comment by ricenoddle** [comment]
I saw that in your demo there is an empty tag for a new line. Maybe I met this problem is because I'm not using the latest version?

**Comment by ricenoddle** [comment]
Do you have a changelog for me to update from 2.12.2 to 3.4.8 ?

**Comment by rtfpessoa** [comment]
> I saw that in your demo there is an empty tag for a new line. Maybe I met this problem is because I'm not using the latest version?

I think that was probably fixed at some point. Do not recall when.

> Do you have a changelog for me to update from 2.12.2 to 3.4.8 ?

The changelog is https://github.com/rtfpessoa/diff2html/releases, but I guess you mean changes you need to do to the code?

Check the readme, the APIs changes a bit but mostly names. The rest is very similar.
Let me know if I can help upgrade.

**Comment by ricenoddle** [comment]
Yes, by looking at your code I find that you have fixed that problem. I will upgrade to the lastest version. Thanks man!
