### ISSUE TITLE
Add support for collapsing files

### ISSUE THREAD

**Issue by hexad** [rtfpessoa/diff2html#427]
In Bitbucket, you are given the option to collapse a certain file, so that only the path+ filename is shown, but the code of the file is hidden.
The option to collapse a certain file would be a great improvement to diff2html, as it helps with the readability of the code significantly.

**Comment by rtfpessoa** [comment]
👋 @hexad, what version are you using?
If you check the [demo](https://diff2html.xyz/demo.html) you can already see a `Viewed` checkbox in the right side of each file header.

**Comment by hexad** [comment]
Hello and thanks!
You are right, i hadn't seen the demo.
I just checked and i have 5.2.1. Is there a way to update from the npm?

**Comment by rtfpessoa** [comment]
Seems like I missed this notification. Not sure what you mean but you can just do `npm install --save diff2html@<VERSION>`

**Comment by hexad** [comment]
Github and npm says that the latest version of diff2html is Version 3.4.17. However when i type `diff2html --version` i get `5.2.1`.

**Comment by rtfpessoa** [comment]
You might be mixing the cli version and the lib version.
*  [diff2html](https://www.npmjs.com/package/diff2html) (corresponds to `diff2html` on the code)  - `3.4.17`
*  [diff2html-cli](https://www.npmjs.com/package/diff2html-cli) (corresponds to `diff2html` on the terminal) - `5.2.2`
