### ISSUE TITLE
Unnecessary horizontal scroll bars appear

### ISSUE THREAD

**Issue by AutismPatient** [rtfpessoa/diff2html#448]
`const diffJSON = computed(()=>{
  return Diff2Html.html(diffs.value,{
    drawFileList: false,
    matching: 'lines',
    outputFormat: 'line-by-line'
  })
})`

diffs: `--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n`

![image](https://user-images.githubusercontent.com/37021551/189057650-16c3e74d-de24-45be-bb7c-97d75677bdc4.png)

Use official documents: [https://github.com/rtfpessoa/diff2html#example-with-vuejs](https://github.com/rtfpessoa/diff2html#example-with-vuejs)

**Comment by rtfpessoa** [comment]
AFAIK that is OS related @AutismPatient. In MacOS it works fine.

Do you know if any change we can make to improve this in other OSes?

**Comment by AutismPatient** [comment]
I can see beauty by editing the style
