### ISSUE TITLE
Viewed button issue + highlight dark theme

### ISSUE THREAD

**Issue by tnhu** [rtfpessoa/diff2html#460]
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: **Mac 12.6. Chrome 108.0.5359.94 (Official Build) (arm64)**
- diff2html version: **3.4.18**
- Using diff2html directly or using diff2html-ui helper: **Both**
- Extra flags: **N/A**

### Step 1: Describe the problem:

- Viewed button does not work since 3.4.18. It does not collapse file content.
- Rendering looks weird when using a dark highlightjs theme. Actually it looks weird with light themes as well.

<img width="674" alt="Screen Shot 2022-12-07 at 11 46 59 PM" src="https://user-images.githubusercontent.com/30633/206388961-078edcc1-7e68-4a0e-9440-b685fb929853.png">

#### Steps to reproduce:

1. Look at example here https://codesandbox.io/s/diff2html-issues-dkur77?file=/src/App.js

#### Observed Results:

- Viewed button does not collapse file content
- Highlightjs themes look weird

#### Expected Results:

- Viewed button should collapse file content
- Highlightjs themes should be rendered nicer 

#### Relevant Code:

Look at https://codesandbox.io/s/diff2html-issues-dkur77?file=/src/App.js to reproduce.

**Comment by tnhu** [comment]
It looks like when I added the required resources:

```
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/diff2html/bundles/css/diff2html.min.css"
    />
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/diff2html/bundles/js/diff2html-ui.min.js"
    ></script>
```

The problems go away, but dark theme is not rendered.

**Comment by rtfpessoa** [comment]
Strange, regarding the view button, everything seems to be working [in the demo](https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=10000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=line-by-line&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&highlightLanguages=[object%20Map]&smartSelection=1&fileContentToggle=1&stickyFileHeaders=1&diff=https://github.com/rtfpessoa/diff2html/pull/106)

I can try to double check with a local version when I am back in the laptop.

**Comment by rtfpessoa** [comment]
Cannot replicate, if you still face the issue please provide a single HTML file where it can be replicated.
