### ISSUE TITLE
side-by-side diff is broken in Firefox

### ISSUE THREAD

**Issue by kuzjka** [rtfpessoa/diff2html#475]
#### Environment

- OS: Windows 10
- Browser: Firefox 108.0.2 (64-bit)
- diff2html version: 3.4.24
- Using diff2html directly or using diff2html-ui helper: directly

Observed with any diff in side-by-side view

#### Observed Results:

Side-by-side is rendered wrongly, see screenshot from the [demo](https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=10000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=side-by-side&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&highlightLanguages=[object%20Map]&smartSelection=1&fileContentToggle=1&stickyFileHeaders=1&diff=https://github.com/rtfpessoa/diff2html/pull/106) below:

![image](https://user-images.githubusercontent.com/1489303/211752257-b02b4ab8-541c-4470-a3e8-47346dce2d37.png)

#### Expected Results:

Side-by-side diff is rendered side-by-side :)

#### Relevant Code:

After reloading demo page 5 minutes later the issue was gone. I found following differences in the CSS:
![image](https://user-images.githubusercontent.com/1489303/211753700-c1ba6402-e02d-4df0-8097-ef6334bf5ca4.png)
left is buggy, right is ok

Looks like the diff2html version on the demo page was changed.

I encountered the issue in my project after migrating from 3.4.17 to 3.4.24, so the issue was introduced somewhere in between.

Sorry for the bitmaps. I can construct specific reproducible example if needed.

**Comment by jrmuizel** [comment]
For fun, I filed a Firefox bug about it: https://bugzilla.mozilla.org/show_bug.cgi?id=1811353

**Comment by rtfpessoa** [comment]
Seems like it was introduced by https://github.com/rtfpessoa/diff2html/commit/df005c3f06335c285987e91474b58ef1f2311f1d
