### ISSUE TITLE
Can't run diff2html-cli on linux docker container

### ISSUE THREAD

**Issue by YodaYakari** [rtfpessoa/diff2html#479]
### Step 0: Describe your environment

- OS: Docker debian/alpine/ubuntu
- diff2html version: 5.2.9
- Using diff2html-cli
- Extra flags: **\_**

### Step 1: Describe the problem:

Nothing seems to be generated from diff2html-cli command.

I have generated a git diff and executed the diff2html-cli command but nos logs and no html output

#### Steps to reproduce:

1. run a docker container
```
docker run debian:latest    Or alpine:latest Or ubuntu:latest
```

2. install nodejs/npm and diff2html-cli
```
apt install -y npm 
npm install -g diff2html-cli
```

3. Generate a diff from two git repos or two directories

4. execute 
```diff2html -i file -F pretty-diff.html -- my-diff.diff ```

#### diff example:

```diff
diff --git describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
   return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
 }
```

#### Observed Results:

- No logs, no html file generated.
- Testing on a a bash with windows it works correctly but when testing in a container, it does not.

#### Expected Results:

- Expecting an html report.

What am i missing ?

**Comment by YodaYakari** [comment]
Not an issue actually, a misunderstanding in parameters caused confusion. The previous code works correctly on all platforms

**Comment by rtfpessoa** [comment]
Then I guess we can close this, right?
