### ISSUE TITLE
Code breaking when there is no change in a line

### ISSUE THREAD

**Issue by ravellaabhinav** [rtfpessoa/diff2html#489]
Suppose if there are 5lines of code to check difference and there are changes in Line:1,2,5. The library is helping to print the difference with line number for line:1,2 and when there is a break in line number i.e.,line5 here line number is not getting printed instead char count number is being printed

### **Error:**
_____________________________________________________________________________________
![image](https://user-images.githubusercontent.com/82701555/234224499-35a9abad-437d-4bbd-ad1e-fb587b51ae49.png)

**Comment by rtfpessoa** [comment]
👋 Can you post here the unified diff you used as input?

**Comment by ravellaabhinav** [comment]
I worked on that issue 3 months back. At present I am not having any samples
