### ISSUE TITLE
Is it possible to generate single html report for multiple git repos?

### ISSUE THREAD

**Issue by vsapronov** [rtfpessoa/diff2html#490]
I'm wondering if there is any way to use diff2html for generating a single file report for multiple git repo?

Here's what I mean:

Input: the folder with multiple repos cloned:
```
/ my-projects
  / repo1
  / repo2
  / repo3
```

Command: `diff2html` in `my-projects` working directory.

Output:
The single html file showing diffs for all 3 repos. Reports should be grouped per repository.

**Comment by rtfpessoa** [comment]
👋 diff2html is a unified diff parsing and html generator tool, meaning that it works with basically the diffs.

If you generate a diff for all those and pass it here it should be fine.

You could do that for example with `git diff --no-index <path-to-dir>/my-projects | diff2html -i stdin`
