### ISSUE TITLE
how to make `diff2html` display line breaks for line-by-line view ??

### ISSUE THREAD

**Issue by yockey1** [rtfpessoa/diff2html#524]
## Issue Description

I am trying to configure `diff2html` to display the diff in line breaks for line-by-line view. I have referred to issues #99 and #97, but I am still unable to achieve the desired functionality. I am aware that there are ongoing efforts to make it work for side-by-side view as mentioned in #99.

I have also noticed similar queries from other users but couldn't find a clear solution. I have checked the comments on #97 ([comment link](https://github.com/rtfpessoa/diff2html/issues/97#issuecomment-615048532)) and #99 ([comment link](https://github.com/rtfpessoa/diff2html/issues/99#issuecomment-525238945)).

### Current Environment and Status
- diff2html version: **3.4.45**
- Using diff2html directly

Any guidance on how to make `diff2html` display line breaks for line-by-line view would be greatly appreciated.

Thank you!

**Comment by rtfpessoa** [comment]
Like the other threads it is not a simple problem to solve.
It would require some css mixed with some configuration to allow maybe swapping classes to make current style and break style work.
Honestly I don't think we need another thread as we have others.
If you find how to make it work let me know.
