### ISSUE TITLE
Backslashes removed in title e.g. C:\dev\alex\test.json -> C:devalex.json

### ISSUE THREAD

**Issue by alexsuter** [rtfpessoa/diff2html#525]
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: everywhere
- diff2html version: latest
- Using diff2html directly or using diff2html-ui helper: diff2html
- Extra flags: not relevant

#### Steps to reproduce:

1. Use a patch with windows paths

#### diff example:

```diff
diff --git a/sample.js b/sample.js
index 0000001..0ddf2ba
--- C:\dev\alex.js
+++ b/sample.js
@@ -1 +1 @@
-console.log("Hello World!")
+console.log("Hello from Diff2Html!")
```

#### Observed Results:

- Backslashes removed in title e.g. C:\dev\alex\test.json -> C:devalex.json

#### Expected Results:

- Backslashes won't be removed

#### Relevant Code:

![image](https://github.com/rtfpessoa/diff2html/assets/7498380/f44e622a-bb76-4695-8024-26e33e20683a)

**Comment by rtfpessoa** [comment]
Cannot replicate the issue on my side.
Also that diff seems manipulated since the header file has a different name from the one in the `+++` tag.
Also the `+++` tag misses the `a/` prefix.

Maybe something specific to windows? I don't have a way to test atm.

**Comment by rtfpessoa** [comment]
Closed due to inactivity
