### ISSUE TITLE
How to hightlight space in new Line?

### ISSUE THREAD

**Issue by Julinear** [rtfpessoa/diff2html#528]
### Step 1: Describe the problem:

![image](https://github.com/rtfpessoa/diff2html/assets/33052315/a49974d4-9b70-47fd-942c-c00f6c92719f)
I get a diff like this:
` 
+                
+sdfs     
+
+234234234234
+1234234
+1           
+serwer     sdf sdf          
+               
`
Now, i need to highlight the space with dark green in a new line; BTW, when it was a remodified line, it works.

Is there any solutions to reslove it?

**Comment by Julinear** [comment]
@rtfpessoa

**Comment by Julinear** [comment]
@stockmind Is there any solutions? Thanks

**Comment by rtfpessoa** [comment]
That is not currently a supported feature.
If you are interested in contributing the code I am happy to hear about it.

**Comment by rtfpessoa** [comment]
Closed due to inactivity, let me know if you are interested in contributing it.
