### ISSUE TITLE
Wrong bower.json::main

### ISSUE THREAD

**Issue by fedescarpa** [rtfpessoa/diff2html#53]
[bower.json::main#L:30](https://github.com/rtfpessoa/diff2html/blob/master/bower.json#L30) should be `dist` instead of `src`

Using wiredep, it throws an error on browser because require function is not defined

**Comment by fedescarpa** [comment]
Thank you for the quick fix.

Would you mind putting the `./dist/diff2html.css` file into the main too?

```json
...
    "main": [
        "./dist/diff2html.js",
        "./dist/diff2html.css",
    ]
...
```

**Comment by rtfpessoa** [comment]
Ok, I thought it was like npm. Just read the docs, and updated.
Thanks for the suggestion.
