### ISSUE TITLE
Documentation Improvement?

### ISSUE THREAD

**Issue by MarketingPip** [rtfpessoa/diff2html#532]
Hello!

It would be great to get some more examples as ES6 import.

I have tried playing with this library all day struggling to figure out what I am doing wrong lol.

The code below should produce a highlighted string. But for some reason - highlighting is not picking up. Plus I am sure there is a pretty  way to do this. 

ps; forced to use this for tests / browser tests from ESM.sh as CDN - tho the default / main script does not catch proper requirements when loaded as ES6 Module..

#### Relevant Code:

```
import   Diff2HtmlUI from "https://esm.sh/diff2html/lib/ui/js/diff2html-ui-slim.js";

import * as JsDiff from "https://esm.sh/diff"
 
 

 

function compare(val1, val2) {
  const diff = JsDiff.createPatch('', 
   val1,
  val2,
    'original', 'modified', { options: { context: 5} }
  );
 document.querySelector("#diff").innerHTML = updateDiff(diff);
}

function updateDiff(diff) {
    const configuration = {
        drawFileList: true,
        matching: 'lines',
        outputFormat: 'side-by-side',
        fileListToggle: false,
        fileListStartVisible: false,
        fileContentToggle: false,
        container: document.createElement('div'),
      diff2htmlUi:null,
       highlight: true 
    };

   configuration.diff2htmlUi = new Diff2HtmlUI.Diff2HtmlUI(configuration.container, diff, configuration);

    configuration.diff2htmlUi.draw();
 
    configuration.diff2htmlUi.highlightCode();
  
  configuration.diff2htmlUi.highlightCode = configuration.container
  
    const HTML = getContentByQuerySelector(configuration.container.outerHTML, ".d2h-files-diff");

    // Remove the container element from the DOM
    configuration.container.remove();

    // Clear all keys in the configuration object
    for (let key in configuration) {
        delete configuration[key];
    }
    return HTML
}

function getContentByQuerySelector(element, selector) {
    // Get the HTML content from the element
    var htmlContent = element

    // Create a new DOMParser
    var parser = new DOMParser();

    // Parse the HTML string into a Document
    var doc = parser.parseFromString(htmlContent, "text/html");

    // Use querySelector on the parsed document to get the content with the given selector
    var selectedContent = doc.querySelector(selector);

    // Return the innerHTML of the selected content
    return selectedContent ? selectedContent.innerHTML : null;
}

 
compare('function example() {\n    return "pizza";\n}' , `function hello(){
console.log("hellos")
}`)
```

**Comment by rtfpessoa** [comment]
I think you are missing the actual CSS, check one example here https://github.com/rtfpessoa/diff2html/blob/master/website/templates/pages/demo/demo.ts

**Comment by MarketingPip** [comment]
@rtfpessoa - it appears you are correct! I thought I tried this (maybe I didn't tho and used a Hightlight.js CSS sheet). 

That said - awesome project tho! Some documenation improvements would probably save a lot of other's headaches.

Thank you for the quick reply! Cheers 🥂

**Comment by rtfpessoa** [comment]
Unless you have some specific thing you feel like contributing to the docs, I feel like there are already examples covering this like https://github.com/rtfpessoa/diff2html?tab=readme-ov-file#stimulusjs-with-typescript

**Comment by MarketingPip** [comment]
@rtfpessoa - fair enough! I'll try to possibly make a PR with some changes / possible improvements to documentation. Keep in mind you did an AWESOME job documenting this. Just I'm the type (lots of others too need it even more dumbed down lol)
