### ISSUE TITLE
Getting the data structure used for HTML rendering (Nodejs use)

### ISSUE THREAD

**Issue by jkavalec** [rtfpessoa/diff2html#533]
Hi,

from demo, It seems this tool has everything I would expect for side by side diff, except that I need render diff within Nodejs environment.

I was looking at docs but couldn't find anything.

Is there any way to get a structure that has all the data used for HTML rendering, so that it could be used in other environments i.e. Nodejs?

**Comment by rtfpessoa** [comment]
👋 So if I understood correctly you want to use just the parsing capabilities?
If yes, here are the docs about the parse API without the rendering https://github.com/rtfpessoa/diff2html?tab=readme-ov-file#diff2html-api

Feel free to reopen if you need more help
