### ISSUE TITLE
Unrecognised input. Possibly missing opening '{'

### ISSUE THREAD

**Issue by THU-Yu** [rtfpessoa/diff2html#537]
- diff2html version: 3.4.48

I encountered the following error:
- Unrecognised input. Possibly missing opening '{'
      in ./node_modules/.pnpm/diff2html@3.4.48/node_modules/diff2html/bundles/css/diff2html.min.css (line 1, column 1743)

It seems that there is a problem with the CSS format.

**Comment by rtfpessoa** [comment]
Can you provide an example of how you got into that error?

**Comment by THU-Yu** [comment]
I use `import 'diff2html/bundles/css/diff2html.min.css';` in my code. I verified the CSS format of version 3.4.48 through [the website](https://toolgg.com/css-validator.html). The error report is as follows. I searched online and found that it might be a problem with [CSS Lint](https://github.com/CSSLint/csslint/issues/720).
![image](https://github.com/user-attachments/assets/3d2cf4f4-3a75-4ea0-994b-41e64baaf850)

**Comment by rtfpessoa** [comment]
I have no idea what it can be seems something specific to your setup.

**Comment by rtfpessoa** [comment]
If you share a simple project with reproducing the error feel free to reopen, otherwise I won't be able to help
