### ISSUE TITLE
 Creating a Custom Render Class in diff2html for Flexible Template Rendering

### ISSUE THREAD

**Issue by weng7654** [rtfpessoa/diff2html#539]
To implement a custom render class, extract the FileListRenderer, LineByLineRenderer, and SideBySideRenderer classes and create a parent class called BaseRenderer. This allows the diff2html config to use a custom render class (which inherits from BaseRenderer). In this way, you can define custom rendering rules for the page, making the template more flexible.

**Comment by rtfpessoa** [comment]
You can already customize the templates which gives plenty of power.
Not clear why you would need to extend renderers.
That would make evolving the code extremely hard and no clear value added.
