### ISSUE TITLE
Separate diff2json parser into a separate project?

### ISSUE THREAD

**Issue by pbu88** [rtfpessoa/diff2html#54]
I've been thinking that some people might find super useful to parse diff output into a json. We already have this in our project, so maybe it will be great to separate it into it's own diff2json project, and use that as an external dependency in diff2html.

This will simplify diff2html project itself and will decouple the parser, so can be reusable.

It shouldn't be too hard to do this.

**Comment by rtfpessoa** [comment]
This all started with a small project, then it was split between CLI and
Library, now json and html.
Need to think about this, maybe it makes sense.

**Comment by pbu88** [comment]
I think it could make the code smaller and its parts reusable, but maybe it could slow development (having to fix stuff or add features in two different projects). I just thought about it and wanted to bring it up :)

**Comment by rtfpessoa** [comment]
I think for now we should keep it as is.
If we experience any issues of has any concerns we can re-evaluate.
