### ISSUE TITLE
jsdiff createPatch always show second file at the end instead of the beginning with html2diff

### ISSUE THREAD

**Issue by ghiscoding** [rtfpessoa/diff2html#540]
### Step 0: Describe your environment

- OS: Windows 10
- diff2html version: 3.4.48
- Using diff2html directly or using diff2html-ui helper: diff2html + jsdiff
- Extra flags: n/a

### Step 1: Describe the problem:

hello, I am using jsdiff with `createPatch()` so that I can use it with `html2diff` for a documentation project, but the resulted patch always seem to append the 2nd file diff (right side) to the end of the patch. This makes the viewing not exactly great for the end user since we have to scroll to either the middle or the end of the file to find the actual diff

Note that I had opened similar jsdiff [issue](https://github.com/kpdecker/jsdiff/issues/541) but it was closed saying that 

> The behaviour you take issue with here isn't actually anything to do with jsdiff. If you log the patch that jsdiff outputs in your
> Nothing in the patch itself hints at which particular lines to position side by side when rendering the deletions and insertions alongside each other. The decision to pair up the `+# General Requirements` insertion with the `-240 VOLTS AC 3 Phase 3 Wire 60 Hertz` deletion is being made entirely by `html2diff`, not by jsdiff.

#### Steps to reproduce:

Here's a codepen of the above issue
https://codepen.io/ghiscoding/pen/wvLpRQd?editors=1000

#### Observed Results:

The diff comparison starts near the end of the file change instead of the beginning of the file

#### Expected Results:

I would expect to see the diff show up on the first line, but instead it showed in the middle of the file (or sometime completely at the end)

#### animated gif of issue

![msedge_IwcravfjtU](https://github.com/user-attachments/assets/8b44eaa7-b568-4755-9839-5372694efaaa)

**Comment by rtfpessoa** [comment]
That is related to the matching algorithm. You decided to use the `lines` you can disable it with `matching: 'none'`
