### ISSUE TITLE
file link to multiple diffs with the same filename always link the the first one

### ISSUE THREAD

**Issue by kintarowins** [rtfpessoa/diff2html#547]
I'm creating a report page that shows diffs from multiple branches e.g.

branchA:
  file1.txt
  file2.txt

branchB:
  file1.txt
  file2.txt

The problem here is that when I click on the link for file1.txt from branchB, it jumps to the diffs of branchA's file1.txt.
I think someone reported a similar [issue]( https://github.com/rtfpessoa/diff2html/issues/510) before and mentioned that this is due to the [simple hash function](https://github.com/rtfpessoa/diff2html/blob/3732d5924906959f40f19b4ba8870c33d16af793/src/render-utils.ts#L188) used for the filename. Is there a way to assign a custom file id instead?

I am using the lastest version available 3.4.24

**Comment by rtfpessoa** [comment]
Not sure I understand what you mean, but how can you end up with a diff where you have the same file twice?
AFAIK one valid diff can only have one file name once.
Let me know if I am interpreting the spec incorrectly.

**Comment by kintarowins** [comment]
You can if you're displaying diffs from multiple repositories or branches. I think it's an appropriate use case if you can imagine you're displaying a diff report in HTML and this is a diff2html library. So this report contains diffs for multiple repositories, and all of them have a common file: config.yml, this is where the hash generated is the same (not unique) and causes the links to always jump to the first config.yml file's diff. It's that simple.

**Comment by rtfpessoa** [comment]
This sounds weird to me as a use case.
In general having the same filename seems bad UX as you don't have a clear differentiator besides the order in the input. 
In general if you have multiple repos, why not prefix the file name with the repo directory on disk also?

**Comment by kintarowins** [comment]
Let's say I have 2 repos using node.js which both have a package.json file, you're suggesting I should rename those with a prefix like REPO1-package.json REPO2-package.json ? There's going to be a lot of other standard framework files as well, do you see how this isn't going to work? Let's simplify even further and forget about the different repos, assume we're on a single repo but with multiple branches, 1.x, 2.x, 3.x, the report needs to compare diffs on package.json on these branches, this is a normal legitimate use case don't you think?

**Comment by kintarowins** [comment]
@rtfpessoa I'd be happy to submit a PR to make this work, what do you think? I believe this would also fix issue https://github.com/rtfpessoa/diff2html/issues/510
