### ISSUE TITLE
Image/picture changes are unable to be displayed 

### ISSUE THREAD

**Issue by johnny-liang-gd** [rtfpessoa/diff2html#548]
### Step 0: Describe your environment

- OS: **macOS**
- diff2html version: **3.4.48**
- Using diff2html directly or using diff2html-ui helper: **diff2html**

#### Steps to reproduce:

1. change some existing icon png etc.
2. git diff
3. The component is unable to display the previous pic and the updated pic

#### diff example:

```diff
diff --git a/ic_share.png b/ic_share.png
index 14e3e11..5089ced 100644
Binary files a/ic_share.png and b/ic_share.png differ
```

#### Observed Results:

- no pic displayed at all
<img width="1695" alt="image" src="https://github.com/user-attachments/assets/88246280-840d-464a-b8e2-b530c4929a51">

#### Expected Results:

- Should display the pic before & after change some UI like below
![image](https://github.com/user-attachments/assets/186e0d4a-e640-457f-aaba-d11924da29ed)

**Comment by rtfpessoa** [comment]
Yes, this is not a supported feature. Contributions are welcome.
