### ISSUE TITLE
Wrong line number for git diff with empty line in C/C++

### ISSUE THREAD

**Issue by duxiaocheng** [rtfpessoa/diff2html#549]
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: **web**
- diff2html version: **latest**
- Using diff2html directly or using diff2html-ui helper: **https://diffy.org/**
- Extra flags: **\_**

#### Steps to reproduce:

1. Input raw diff as below:
```diff
diff --git a/Entry.cpp b/Entry.cpp
index 6cf7f6e..8769d17 100644
--- a/Entry.cpp
+++ b/Entry.cpp
@@ -553,7 +553,7 @@
     }

     NodeList *linkNodeList = mLinkList;
-    int i = 0;
+    unsigned int i = 0;

     while(linkNodeList)
     {
```

#### Observed Results:

The empty line 554 is removed from the parsed result by mistake.
This will result in wrong line number.
https://diffy.org/diff/0bd4ea71e727e
![image](https://github.com/user-attachments/assets/7b91cbc1-cbbd-4619-91ef-193b2b3d1997)

#### Expected Results:

Correct line number.

**Comment by rtfpessoa** [comment]
diff2html works as expected, the problem on your side is possibly that you lost the empty space ` ` that needs to exist in the empty lines for it to be a valid diff.
If the line has no space `` it is not a valid diff line.

Reopen if you invoke diff2html with the file I attached and call it with `diff2html -i file -- ./test.txt` it works fine.

[test.txt](https://github.com/user-attachments/files/18233024/test.txt)

**Comment by duxiaocheng** [comment]
> diff2html works as expected, the problem on your side is possibly that you lost the empty space ` ` that needs to exist in the empty lines for it to be a valid diff. If the line has no space it is not a valid diff line.
> 
> If you invoke diff2html with the file I attached and call it with `diff2html -i file -- ./test.txt` it works fine.
> 
> [test.txt](https://github.com/user-attachments/files/18233024/test.txt)
> 
> Reopen if you have a file that breaks this and is a valid diff.

Yes, you are right. Thanks for your reply!
