### ISSUE TITLE
Fix diff parsing on windows line ending

### ISSUE THREAD

**Issue by rtfpessoa** [rtfpessoa/diff2html#57]
Copied from [https://github.com/rtfpessoa/diff2html-cli/issues/16](https://github.com/rtfpessoa/diff2html-cli/issues/16)

when the diff diff2html-cli is given, has CRLF line endings, the generator will generate a valid html file, but it will act as if the source diff was empty.

obviously, this isn't ideal on windows -- especially when everything is so hard coded (cmd, powershell) to always output \r\n.

i'm not sure how fixable this is for you, or if it touches the entire code base (hope not). presently i'm running dos2unix on the diffs i create from hg, but of course that is a real hack and has its own pitfalls.

**Comment by pbu88** [comment]
It also has an impact when receiving the diff via a <textarea> html element. Textarea uses CRLF line endings.

**Comment by rtfpessoa** [comment]
@pbu88, any suggestions of libs to perform the EOL conversion?

**Comment by pbu88** [comment]
Hmmm I think this is fair easy fix. At some point in the parser we do this:

    //dir-parser.js line 125
    var diffLines =
      diffInput.replace(/\\ No newline at end of file/g, '')
        .split('\n');

So we could basically change all the \r\n into \n or we could do a smarter split.

**Comment by rtfpessoa** [comment]
That seemed like a very aggressive way. But maybe it is simple enough to try it.

**Comment by pbu88** [comment]
Well, I think this is a relatively easy to fix issue. Using an external library might be overkill. Maybe I'm failing to see a future issue that this fix might involve.
