### ISSUE TITLE
Allow to copy code without line numbers.

### ISSUE THREAD

**Issue by lantian** [rtfpessoa/diff2html#64]
It would be great if lines was not copied within code selection. Example https://codemirror.net/

Possible solution: http://jsbin.com/runomuheye/1/edit?html,css,js,output

P.S. Good job! Great project!

**Comment by rtfpessoa** [comment]
That looks good. If you want to contribute the change it would fit in the `diff2html-ui.js`.

**Comment by lantian** [comment]
Yep, maybe I will try to implement this in nearest week. But still can not decide is it ok to use js for that, or proper is implement different html layout.

**Comment by rtfpessoa** [comment]
I usually do not like HTML/CSS, and since I do not have much experience doing it, the current choices might be wrog.

I am open for better alternatives.

**Comment by lantian** [comment]
And what about such implementation http://jsbin.com/runomuheye/1/edit?html,css,js,output ? As far as I understand meny js codetools using such way
