### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by andfs** [rtfpessoa/diff2html#66]
I have an app that integrates with github and a self-hosted gitlab. How can I use your package to show diff between a master branch and a pull/merge request in my app?

**Comment by rtfpessoa** [comment]
Hi @andfs,

This project is a simple Javascript library to parse diffs and output either the diff information in `JSON` or pretty `HTML`.

Basically you create a diff with `git diff master your-pr-branch` and the exact output that comes from git goes as input for diff2html.

This is not suited for people that just want to have a pretty diff and share it with co-workers etc.
For that, I created [diff2html-cli](https://github.com/rtfpessoa/diff2html-cli) which is a cli interface for diff2html.

It acts as an intermediary between git and your browser, file etc.
With [diff2html-cli](https://github.com/rtfpessoa/diff2html-cli) you can run the "same" command as with git: `diff2html -- master your-pr-branch` (the `--` is separation between the tool parameters and the git diff parameters).

It allows you to output an html that can be opened in your browser or upload it to [diffy.org](https://diffy.org/) which gives you a permanent link.

[diff2html-cli](https://github.com/rtfpessoa/diff2html-cli) is also customizable through parameters to choose the type of diff, types of outputs inputs etc.

I am not sure what are you exactly looking for, but hope my answer clears your questions.

**Comment by andfs** [comment]
Thanks @rtfpessoa . You'v cleared my doubts. I was trying to find out what goes to diff2html input.
My app get the diff from github/gitlab via rest, so I was in doubt what to use in diff@html.

I'll try it later. thanks for listening :)
