### ISSUE TITLE
Parse valid unidiffs

### ISSUE THREAD

**Issue by adius** [rtfpessoa/diff2html#72]
This is a valid unidiff

```diff
--- a/sample
+++ b/sample
@@ -11 @@
-test
+test1r
```

but diff2html only returns

```html
<div class="d2h-wrapper">
    
</div>
```

When I add `diff` to the beginning of the unidiff, however, it works:

```diff
diff--- a/sample
+++ b/sample
@@ -11 @@
-test
+test1r
```

**Comment by rtfpessoa** [comment]
The code was initially done to Parse only git diffs. Since they are similar I am thinking of doing compatibility for both but did not git time yet.

I will look at this when I get some time today or tomorrow.

**Comment by adius** [comment]
Actually the git diff is just a normal unidiff.
Every line which does not start with a `space`, `+`, `-` or `@` is just a comment....
Thanks for looking into this!

**Comment by rtfpessoa** [comment]
This was fixed in #73 let me know if you have any other cases where it fails.

Released under version `2.0.0-beta18`.

**Comment by beebek** [comment]
I have following code snippet for which diffs are not getting highlighted.

        <script>
            var lineDiff = `diff a/sample b/sample
    --- a/sample
    +++ b/sample
    @@ -11 @@
    -test
    +test1r`;
            document.addEventListener("DOMContentLoaded", function() {
                var diff2htmlUi = new Diff2HtmlUI({diff: lineDiff});
                diff2htmlUi.draw('#line-by-line', {inputFormat: 'json', outputFormat: 'line-by-line', matching:'words'});
                diff2htmlUi.highlightCode('#side-by-side');
            });
        </script>

<img width="181" alt="screen shot 2017-10-09 at 9 40 01 am" src="https://user-images.githubusercontent.com/1183800/31349397-f7849fda-acd7-11e7-91a4-d86297b16df1.png">

But if there is preceding or succeeding line, the diffs are getting highlighted. Am I missing something? 
Checked with diff2html ie `diff a/sample b/sample | diff2html -i stdin --style line` which is giving proper highlighted html page.
            
        var lineDiff = `diff a/sample b/sample
    --- a/sample
    +++ b/sample
    @@ -11 @@
    -test
    +test1r
    this_will_highlight_above_change`;

<img width="351" alt="screen shot 2017-10-09 at 9 39 44 am" src="https://user-images.githubusercontent.com/1183800/31349391-ebd92b10-acd7-11e7-9481-1c3d6c0a95f9.png">

**Comment by rtfpessoa** [comment]
Hi @beebek  you are drawing in `#line-by-line` and highlighting on `#side-by-side`

**Comment by beebek** [comment]
Hi, @rtfpessoa sorry for the typo, actually I am drawing on `#line-by-line` div.

**Comment by rtfpessoa** [comment]
Also I am not sure what you want to highlight. That is not code so not sure what is the highlight

**Comment by beebek** [comment]
Thanks for that quick reply. Please check this.
<img width="1042" alt="screen shot 2017-10-09 at 11 03 09 am" src="https://user-images.githubusercontent.com/1183800/31351872-8cde3b32-ace1-11e7-8657-f220f4509690.png">

```html
    <script>
        var lineDiff = 
'diff -U 1 /tmp/asdfjson /tmp/asdfasdf.F1PQ6n.json\n' +
'--- /tmp/asdf.json   2017-10-06 14:09:23.000000000 -0700\n' +
'+++ /tmp/asdf.json   2017-10-06 14:09:23.000000000 -0700\n' +
'@@ -4141,3 +4197,3 @@\n' +
'-               "description":""Experience null",\n' +
'+               "description":null,\n' +
'addition\n' +
'@@ -4173,3 +4229,3 @@\n' +
'-               "description":"false null",\n' +
'+               "description":null,\n' +
'addition\n' +
'\n';
        document.addEventListener("DOMContentLoaded", function() {
            var diff2htmlUi = new Diff2HtmlUI({diff: lineDiff});
            diff2htmlUi.draw('#side-by-side', {inputFormat: 'json', outputFormat: 'side-by-side', matching:'words'});
            diff2htmlUi.highlightCode('#side-by-side');
        });
    </script>
```
if I do not have that `addition` line, it will basically not highlight the changes as in the screenshot.

**Comment by rtfpessoa** [comment]
Ahh I see what you mean now.

Highlight is a very hardcore feature since it relies on filenames to detect the language and with partial snippets the job is even harder. I am using highlight.js but this case might just be a problem with the few information.

Since the filename is not correctly grabbed the job of the highlight is even harder. So I guess there is not much to do here.

Are you using git diff or diff from gnu tools?

**Comment by beebek** [comment]
I am using diff.
```
$ diff --version
diff (GNU diffutils) 2.8.1
...
...
```

The same diff content is correctly rendered by diff2html from terminal though. e.g. 
`diff -U 0 /tmp/content1.json /tmp/content2.json | diff2html -i stdin --style side`

**Comment by rtfpessoa** [comment]
Wow that is weird. They are both the same. Just a CLI wrapper.
