### ISSUE TITLE
Use semver correctly

### ISSUE THREAD

**Issue by adius** [rtfpessoa/diff2html#74]
I just wanted to upgrade to the latest version (`^2.0.0-beta18`) of diff2html by running `npm up --save diff2html`
But because you used semver the wrong way it installed `^2.0.0-beta9`.
(Which is the specified behavior if you check http://semver.org/#spec-item-11)

To get the correct order you must separate beta and the number with a dot (`^2.0.0-beta.18`)

As `beta` comes lexicographically before `beta9` there is no easy way to fix this with the beta naming schema. I'd propose you switch to release candidate: `^2.0.0-rc.1` and deprecate all beta versions.

```bash
npm deprecate diff2html@'>1.3.2 <2.0.0-rc.1' 'Incorrect version identifiers'
```

**Comment by adius** [comment]
Btw:
This is really important and should be fixed **asap**.
At the moment almost nobody gets the expected version!

**Comment by rtfpessoa** [comment]
I was really thinking I was using this right.

@adius, thanks a lot for the heads up.

Can you please check it is fixed?

**Comment by adius** [comment]
No problem ;-) Looks good!
Thanks for your fast response!

**Comment by adius** [comment]
Btw: You should check out https://docs.npmjs.com/cli/version .
It's super useful npm subcommand for releasing new versions! 
It automatically creates the corresponding commit and tag.
Actually I'd even go so far to say that this should be the only way to create new versions!
Then it's also impossible to create invalid version numbers ;-)

**Comment by rtfpessoa** [comment]
Cool 😄 

I just checked it, and did some changes to the scripts I use for releases.

It should be smother now. Really appreciated your help 👍

**Comment by adius** [comment]
Haha thx for posting on hackernews. 😂
Had a funny encounter with myself: https://twitter.com/AdrianSieber/status/729028804518289408

**Comment by rtfpessoa** [comment]
Hahaha, amazing.

I though it could be a good guide/example for other people 😄
