### ISSUE TITLE
Highlight is working not as supposed

### ISSUE THREAD

**Issue by lantian** [rtfpessoa/diff2html#75]
It applies on line... but not on code block. For fast understanding here is a screenshot:

![spectacle z25642](https://cloud.githubusercontent.com/assets/535545/15094872/43bac94a-14ba-11e6-930c-cdeb3ea820b0.png)

1. It is applying on each line separatly. When it on the comment block - it doesn't understand that this is a comment block.
2. It is applying on whole block. And now it is know about comment block.

It seems that with current approach (applying on line) it is not possible to allow normal highlight. Any ideas?

**Comment by rtfpessoa** [comment]
Yup, that is quite bad.

I had one idea to try solving that problem.
It seems to improve overall highlight but still doesn't fix java comments.

The idea is to invoke highlight in the block and then inject the highlighted lines of the block in the HTML again.

I did one commit here: https://github.com/rtfpessoa/diff2html/commit/a48209797050289f8b2a3ac2f270ab80a27b5464

**Comment by lantian** [comment]
Haha, I have tried such thing yesterday, too! =).  Yup, not closed span problem =).

**Comment by rtfpessoa** [comment]
Thanks to @isagalaev I was able to fix the highlight in https://github.com/rtfpessoa/diff2html/commit/626daccd0202b96725223ed2db26dcc790feab81 .

Now highlight should be perfect except for cases where the diff
context is not enough to understand what is the code.

**Comment by lantian** [comment]
Wow! This is great! Thank you very much!

**Comment by lantian** [comment]
Found new problem, now it looses "hljs" class and language class:
Was:
![1](https://cloud.githubusercontent.com/assets/535545/15107665/b47c71a4-15d9-11e6-8952-405e6c7abdb2.png)

Now:
![2](https://cloud.githubusercontent.com/assets/535545/15107668/b8d8eb6a-15d9-11e6-83ec-5592b7571945.png)

**Comment by lantian** [comment]
Missing buildClassName function (from highlight API). But currently I don't where it must be. Will try to find correct place.

**Comment by rtfpessoa** [comment]
@lantian should be fixed here https://github.com/rtfpessoa/diff2html/commit/8a34346ccb0a2faa5d5a55c0587151ee34ae21b9

**Comment by lantian** [comment]
Yes! Thanks!

**Comment by rtfpessoa** [comment]
BTW, I also have another but in mind. And I will try to fix it soon.

Basically we have two code snippets in each diff, the old and the new.
If we parse them together it might not make sense. I will fix this by having two states one for each part.
And this way it should be even more accurate.

**Comment by rtfpessoa** [comment]
@lantian should be fixed here https://github.com/rtfpessoa/diff2html/commit/73999bb78268816dec7539640df0d55c1b1adb61

**Comment by lantian** [comment]
Seems to be ok! Thank you!

**Comment by rtfpessoa** [comment]
I will see if there are any more problems and will probably deploy this soon.

**Comment by lantian** [comment]
:+1:

**Comment by isagalaev** [comment]
If you guys don't mind me to weigh in, you probably don't need `buldSpan()` or any code from highlight.js itself to assign two classes on a container. "hljs" is a constant, and it looks like you know the language name anyway, since you call `highlight()` with it (and I'm not sure you even need the language in the class attribute).

All this of course is up to you, I'm just pointing out that assigning classes to an outside container is not tied to the highlighting process in any way.

**Comment by rtfpessoa** [comment]
@lantian noticed that some colors where not being correctly set without the classes.

I am not sure if it was depending on `hljs` and the language or just `hljs`.

In my case I only know the one of the language alias, usually the extension.

@isagalaev do you think it might work only with `hljs`?

**Comment by isagalaev** [comment]
> Edit: I checked the CSS and they seem language agnostic.

Yes, this was an express design goal for a big refactoring a while ago. Provided you're on version 9 or later.

> do you think it might work only with hljs?

You shouldn't even need that. The only stuff that gets assigned to ".hljs" class itself is this:

```css
.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: ... ; color: ... ;
}
```

And you have your own block formatting rules and base colors, I believe.

**Comment by rtfpessoa** [comment]
@isagalaev actually it was @lantian not sure what were the custom colors he was using.

fyi, this was released as version `2.0.0-rc.3`.

**Comment by isagalaev** [comment]
Cool! Always nice to see highlight.js being used in some interesting fashion :-)

**Comment by lantian** [comment]
The theme was: "Sunburst-like style (c) Vasily Polovnyov <vast@whiteants.net>"
And exactly missing ".hljs" class was a problem - that class is defined in theme (with css color property) and wasn't provided by the script. From that point I have no any custom css related to highlight =), only for diff2html.
