### ISSUE TITLE
Question: Diff2Html.getJsonFromDiff is not a function

### ISSUE THREAD

**Issue by georgeedwards** [rtfpessoa/diff2html#94]
I am trying to follow your docs, but haven't found any examples of usage, or function signature docs, have I missed something?

Without the above, I have guessed and created a script like this:

```
var fs = require('fs');
var Diff2Html = require('diff2html');
function processTutorial() {
    var files = [];
    var _files = getFiles('./tutorial/patches', files);
    var _loop_1 = function(path) {
        fs.readFile(path, 'utf8', function (err, data) {
            if (err) {
                throw err;
            }
            var content = Diff2Html.getJsonFromDiff(data);
            writeFile(content, path);
        });
    };
    for (var _i = 0, _files_1 = _files; _i < _files_1.length; _i++) {
        var path = _files_1[_i];
        _loop_1(path);
    }
}
```
Note - it's slightly ugly because it's compiled from typescript. When this is run, I get the following error:

```
Repos\docs\prepareTutorial.js:13
            Diff2Html.getPrettyHtml(data, { outputFormat: 'side-by-side' });
                      ^

TypeError: Diff2Html.getPrettyHtml is not a function
    at C:\Users\George\Source\Repos\docs\prepareTutorial.js:13:23
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

What have I done wrong?

NB: 

>npm list diff2html
docs@0.0.0 C:\Users\George\Source\Repos\docs
`-- diff2html@2.0.1

**Comment by rtfpessoa** [comment]
Hi @georgeedwards 

The API is basically defined by:

```
  /*
   * Generates json object from string diff input
   */
  Diff2Html.prototype.getJsonFromDiff = function(diffInput, config)

  /*
   * Generates the html diff. The config parameter configures the output/input formats and other options
   */
  Diff2Html.prototype.getPrettyHtml = function(diffInput, config) 

/* DEPRECATED METHODS */

  /*
   * Generates pretty html from string diff input
   */
  Diff2Html.prototype.getPrettyHtmlFromDiff = function(diffInput, config)

  /*
   * Generates pretty html from a json object
   */
  Diff2Html.prototype.getPrettyHtmlFromJson = function(diffJson, config)

  /*
   * Generates pretty side by side html from string diff input
   */
  Diff2Html.prototype.getPrettySideBySideHtmlFromDiff = function(diffInput, config)

  /*
   * Generates pretty side by side html from a json object
   */
  Diff2Html.prototype.getPrettySideBySideHtmlFromJson = function(diffJson, config)
```

And I have some docs about parameters etc here: https://github.com/rtfpessoa/diff2html#how-to-use

You can also find some real usage examples in the UI helper I have here: https://github.com/rtfpessoa/diff2html/blob/master/src/ui/js/diff2html-ui.js

The error is probably because you need: `require('diff2html').Diff2Html` instead of `require('diff2html')`.

Let me know if I can help you with any more information.

**Comment by georgeedwards** [comment]
Thanks! It would be good to add that example to the README docs? The functions seem to return strings? Would you like me to put together a definition file for TS in a PR?

**Comment by rtfpessoa** [comment]
I know nothing about ts definitions. I can try.

When I have some time I can look into it.

**Comment by georgeedwards** [comment]
Awesome - that'd be great. This is what I got which I believe fully describes the two main functions, just not the UI helper stuff.

```
declare module 'diff2html' {
    function getPrettyHtml(exInput: string, configuration: options): string;
    function getJsonFromDiff(exInput: string): string;
}

interface options {
    inputFormat?: string;
    outputFormat?: string;
    showFiles?: boolean;
    matching?: string;
    synchronisedScroll?: boolean;
    matchWordsThreshold?: number;
    matchingMaxComparisons?: number;
}
```

**Comment by rtfpessoa** [comment]
That seems to be it. I will give the code a check to see if the docs are missing something.

**Comment by rtfpessoa** [comment]
@georgeedwards sorry for the delay.

There is one thing that can be more specified. In `getJsonFromDiff` it returns an object and that object has some properties. I will try to make some interfaces for it.

**Comment by rtfpessoa** [comment]
@georgeedwards, just finished it, what do you think? 

```
// Type definitions for diff2html
// Project: https://github.com/rtfpessoa/diff2html
// Definitions by: georgeedwards <https://github.com/georgeedwards/>
//                 rtfpessoa <https://github.com/rtfpessoa/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare namespace Diff2Html {
    
	interface Diff2HtmlOptions {
	    inputFormat?: string;
	    outputFormat?: string;
	    showFiles?: boolean;
	    matching?: string;
	    synchronisedScroll?: boolean;
	    matchWordsThreshold?: number;
	    matchingMaxComparisons?: number;
	}

    interface DiffLine {
		content: string;
		type: number;
		oldNumber: number;
		newNumber: number;
	}

    interface DiffBlock {
		oldStartLine: number;
		oldStartLine2?: number;
		newStartLine: number;
		header: string;
		lines: DiffLine[];
	}

    interface DiffResult {
		addedLines: number;
		deletedLines: number;
		isCombined: boolean;
		isGitDiff: boolean;
		oldName: string;
		newName: string;
		language: string;
		blocks: DiffBlock[];
		oldMode?: string;
		newMode?: string;
		deletedFileMode?: string;
		newFileMode?: string;
		isDeleted?: boolean;
		isNew?: boolean;
		isCopy?: boolean;
		isRename?: boolean;
		unchangedPercentage?: number;
		changedPercentage?: number;
		checksumBefore?: string;
		checksumAfter?: string;
		mode?: string;
	}
    
    function getJsonFromDiff(input: string, configuration?: Diff2HtmlOptions): string;

    function getPrettyHtml(input: string, configuration?: Diff2HtmlOptions): DiffResult;
}

declare module "diff2html" {
    export = Diff2Html;
}
```

Where is this supposed to go? Should I PR it to DefinitelyTyped?

**Comment by georgeedwards** [comment]
Awesome! Looks good to me! Yes PR the [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) repo, [here](http://definitelytyped.org/guides/contributing.html) is the contributing guide if you need any more info.

**Comment by rtfpessoa** [comment]
Just tried the test but I cannot seem to make it work.

Due to the `var Diff2Html = require('diff2html').Diff2Html ;`

I have no idea how to write the `declare module`. This one is wrong.

Do you have any idea how to do it?

**Comment by rtfpessoa** [comment]
I think now is fine:

```
// Type definitions for diff2html
// Project: https://github.com/rtfpessoa/diff2html
// Definitions by: georgeedwards <https://github.com/georgeedwards/>
//                 rtfpessoa <https://github.com/rtfpessoa/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare namespace Diff2Html {
    
	export interface Options {
	    inputFormat?: string;
	    outputFormat?: string;
	    showFiles?: boolean;
	    matching?: string;
	    synchronisedScroll?: boolean;
	    matchWordsThreshold?: number;
	    matchingMaxComparisons?: number;
	}

    export interface Line {
		content: string;
		type: string;
		oldNumber: number;
		newNumber: number;
	}

    export interface Block {
		oldStartLine: number;
		oldStartLine2?: number;
		newStartLine: number;
		header: string;
		lines: Line[];
	}

    export interface Result {
		addedLines: number;
		deletedLines: number;
		isCombined: boolean;
		isGitDiff: boolean;
		oldName: string;
		newName: string;
		language: string;
		blocks: Block[];
		oldMode?: string;
		newMode?: string;
		deletedFileMode?: string;
		newFileMode?: string;
		isDeleted?: boolean;
		isNew?: boolean;
		isCopy?: boolean;
		isRename?: boolean;
		unchangedPercentage?: number;
		changedPercentage?: number;
		checksumBefore?: string;
		checksumAfter?: string;
		mode?: string;
	}
    
    export interface Diff2Html {
	    getJsonFromDiff(input: string, configuration?: Options): Result;
	    getPrettyHtml(input: any, configuration?: Options): string;
    }
}

declare module "diff2html" {
	var d2h: { "Diff2Html": Diff2Html.Diff2Html };
    export = d2h;
}
``

Can you test if it works?`

**Comment by rtfpessoa** [comment]
@georgeedwards, just did a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10681

**Comment by rtfpessoa** [comment]
@georgeedwards take a look ate the published version. And let me know if it works.

**Comment by dilips86** [comment]
@rtfpessoa 
I'm trying to use the Diff2HtmlUI for two json comparison like below as per doc.  
`var diff2htmlUi = new Diff2HtmlUI({diff: lineDiffExample});`
Trying in Angular 2.

Squawking with error saying Diff2HtmlUI() is not a defined constructor?

Can you provide help how to integrate in Angular2 to compare two json objects and highlight the differences?

**Comment by rtfpessoa** [comment]
@dilips86. I never used Angular so I am not sure if I can help.

Also diff2htmlui does not have a typescript definition, only diff2html has.

Maybe you can check https://github.com/rtfpessoa/diff2html/issues/146 and see if it helps you.

**Comment by dilips86** [comment]
@rtfpessoa Thanks . Will check.

**Comment by dilips86** [comment]
@rtfpessoa Hey thanks. Anyways I figured it out the issue and fixed it. It works fine with difference highlighting as well with diff2html itself and not using diff2htmlUi.

Would also like to know, is there any API or functionality that will do highlighting the differences and still displays the entire json/string contents? Currently it shows only the differences [diff patch] snippets.

**Comment by rtfpessoa** [comment]
@dilips86 diff2html does not generate any kind of diff. For you to have the full file you need to tell git to give you more context and pass a parameter to git like [this](https://git-scm.com/docs/git-diff#git-diff--Ultngt).

**Comment by Caiyeon** [comment]
@dilips86 were you able to get Diff2HtmlUi working? I'm seeing the same error 
`"TypeError: Diff2HtmlUI is not a constructor"`
when importing via `require('diff2html/dist/diff2html-ui.js')`.
I'm not sure if this is because the Diff2HtmlUI constructor was never exported or if I'm missing something.
