### ISSUE TITLE
Wordwrap function

### ISSUE THREAD

**Issue by codingtwinky** [rtfpessoa/diff2html#97]
diff2html 2.0.1 is working well for us at Ungit and I was able to fix our custom css bindings relatively easy from 1.6.x.  Except for one feature, word wrap. 

CSS word-wrap will not work with diff2html's resulting html code as it is not using actual whitespace, it is using `&nbsp`.  Because of once easy CSS class injection fix for this feature is no longer viable. 

1. What is the reasoning behind the replacing spaces with `&nbsp`?
2. Can we have a word wrap feature support from diff2html?  (I'd rather not have to run the html gen function again)

**Comment by rtfpessoa** [comment]
Dam. I knew this would come to hunt me. Even with more tests. Can never get rid of problems. 😒 

This is related to the code formatting. I will look into it. I need to use `word-wrap: pre;` and then be able to have the html to not go crazy.

Will let you know as soon as I can get this.

**Comment by rtfpessoa** [comment]
@codingtwinky just added a fix in #98

Please take a look and if you can test it.

I will merge it probably tomorrow or something like that.
I just need to have a better look and see if nothing else is broken.
Since this changes some big CSS stuff.

**Comment by rtfpessoa** [comment]
@codingtwinky this should be fixed in `diff2html@v2.0.4`

**Comment by rtfpessoa** [comment]
@codingtwinky after release 2.0.4 I found some problem with the line css, now it should be fixed in `diff2html@v2.0.6`

**Comment by TiredFalcon** [comment]
I have been trying to get the diff (in lines mode) to work for some time but I cannot figure it out.
The `<table>` element inside the code wrapper overflows.
@jung-kim how did you manage to get the line wrapping to work?
